#!/bin/bash

ARGV="$@"

if [ -z "$XTDC_BASE_DIR" ]; then
    echo 'XTDC_BASE_DIR is unset - did you forget to source xtdc/xtdc.env?';
    exit 1;
fi

# Logging Progect test-only behaviour cribbed from:
# https://gitosis/cgit/xt/commit/t/TEST?id=b1e9d0a4e41ebc916a9712c363f31693dab1ca52
# FYI: the path comes from nap.properties and is glued with the filename later in the process
#  - have a look in XTracker::Logfile for more details
XT_LOGCONF='xtracker.conf';

XTDC_APP_LISTEN=:${XTDC_APP_LISTEN:-8529};
XT_PSGI_PIDFILE=${XT_PSGI_PIDFILE:-${XTDC_BASE_DIR}/tmp/plackup.psgi.pid};

XT_CONFIG_LOCAL_SUFFIX=${XT_CONFIG_LOCAL_SUFFIX:-test_intl};
XT_USE_PROXY=${XT_USE_PROXY:-1};

# the normal AMQ Consumer (not the PSP Consumer)
XT_DC_MESSAGING_CONF_FILE=${XTDC_CONF_DIR}/xt_dc_messaging.conf;

XT_AMQ_BROKER_PATH="${XTDC_BASE_DIR}/t/scripts/active_mq_daemon.pl";
if [ ! -f $XT_AMQ_BROKER_PATH ]; then
    echo "${XT_AMQ_BROKER_PATH}: file missing";
    exit 2;
fi

XT_PSGI_APP="${XTDC_BASE_DIR}/xt.psgi";
if [ ! -f $XT_PSGI_APP ]; then
    echo "${XT_PSGI_APP}: file missing";
    exit 2;
fi

# usually we stop the broker; this is a throwback to the apache based script
if [ -z "$NOAMQ" ]; then
    echo "[ Stopping: AMQ daemon (legacy precaution)]";
    XT_DC_MESSAGING_CONFIG=$XT_DC_MESSAGING_CONF_FILE ${XT_AMQ_BROKER_PATH} stop;
fi

for ARG in $@ $ARGS; do
    case $ARG in
        start|-start|restart|-restart)
            if [ -f $XT_PSGI_PIDFILE ]; then
                echo "[ Already running (pidfile exists: ${XT_PSGI_PIDFILE}) ]";
                $0 -stop;
                #exit 3;
            fi

            # start the AMQ broker
            if [ -z "$NOAMQ" ]; then
                echo "[ Starting: run AMQ daemon]";
                XT_DC_MESSAGING_CONFIG=$XT_DC_MESSAGING_CONF_FILE ${XT_AMQ_BROKER_PATH} start;
                echo "[Completed: run AMQ daemon]";
            fi

            # prepare the command to run; store it so we can echo it for
            # debugging
            _args="-s Starman \
                --error-log t/logs/error_log \
                --access-log t/logs/access_log \
                --listen $XTDC_APP_LISTEN \
                --pid $XT_PSGI_PIDFILE \
                --nproc 2 \
                --workers 2 \
                --daemonize \
                -E test \
                $XT_PSGI_APP";
            echo "[ Starting: plackup server]";
            plackup  $_args;
            echo "[  Running: plackup (pid `cat $XT_PSGI_PIDFILE`)]";
            echo "[ Starting: PSGI Debugging]";
            ps -ef |grep [s]tarman;
            lsof -Pp $(cat tmp/plackup.psgi.pid) |grep $XTDC_APP_LISTEN;
            echo "[Completed: PSGI Debugging]";
        ;;

        stop|-stop)
            if [ -f $XT_PSGI_PIDFILE ]; then
                echo "[  Killing: pid `cat $XT_PSGI_PIDFILE`]";
                kill -15 `cat $XT_PSGI_PIDFILE`;
            else
                echo "${XT_PSGI_PIDFILE}: file not found";
            fi
        ;;

        *)
        echo 'Whut?!';
        ;;
    esac
done
