BEGIN;
	INSERT INTO web_content.field(id, name) VALUES ( 241, 'Page 23');
	INSERT INTO web_content.field(id, name) VALUES ( 242, 'Page 24');
	INSERT INTO web_content.field(id, name) VALUES ( 243, 'Page 25');
	INSERT INTO web_content.field(id, name) VALUES ( 244, 'Page 26');
	INSERT INTO web_content.field(id, name) VALUES ( 245, 'Page 27');
	INSERT INTO web_content.field(id, name) VALUES ( 246, 'Page 28');
	INSERT INTO web_content.field(id, name) VALUES ( 247, 'Page 29');
	INSERT INTO web_content.field(id, name) VALUES ( 248, 'Page 30');
	INSERT INTO web_content.field(id, name) VALUES ( 249, 'Page 31');
	INSERT INTO web_content.field(id, name) VALUES ( 250, 'Page 32');
	INSERT INTO web_content.field(id, name) VALUES ( 251, 'Page 33');
	INSERT INTO web_content.field(id, name) VALUES ( 252, 'Page 34');
	INSERT INTO web_content.field(id, name) VALUES ( 253, 'Page 35');
	INSERT INTO web_content.field(id, name) VALUES ( 254, 'Page 36');
	INSERT INTO web_content.field(id, name) VALUES ( 255, 'Page 37');
	INSERT INTO web_content.field(id, name) VALUES ( 256, 'Page 38');
	INSERT INTO web_content.field(id, name) VALUES ( 257, 'Page 39');
	INSERT INTO web_content.field(id, name) VALUES ( 258, 'Page 40');
	INSERT INTO web_content.field(id, name) VALUES ( 259, 'Page 41');
	INSERT INTO web_content.field(id, name) VALUES ( 260, 'Page 42');
	INSERT INTO web_content.field(id, name) VALUES ( 261, 'Promo Block 1');
	INSERT INTO web_content.field(id, name) VALUES ( 262, 'Promo Block 2');
	INSERT INTO web_content.field(id, name) VALUES ( 263, 'Promo Block 3');
	INSERT INTO web_content.field(id, name) VALUES ( 264, 'Promo Block 4');
	INSERT INTO web_content.field(id, name) VALUES ( 265, 'Promo Block 5');
	INSERT INTO web_content.field(id, name) VALUES ( 266, 'Promo Block 6');
	INSERT INTO web_content.field(id, name) VALUES ( 267, 'Promo Block 7');
	INSERT INTO web_content.field(id, name) VALUES ( 268, 'Promo Block 8');
	INSERT INTO web_content.field(id, name) VALUES ( 269, 'Promo Block 9');
	INSERT INTO web_content.field(id, name) VALUES ( 270, 'Promo Block 10');

	SELECT setval('web_content.field_id_seq'::regclass, 271);
COMMIT;