package Test::XTracker::DHL::XMLDocument;
use NAP::policy 'test', 'class';

=head1 NAME

Test::XTracker::DHL::XMLDocument

=head1 DESCRIPTION

Unit tests for the XTracker::DHL::XMLDocument class

=cut

BEGIN { extends 'NAP::Test::Class' };

use XTracker::DHL::XMLDocument;

sub test__parse_label_response_xml :Tests {
    my ($self) = @_;

    for my $test (
        {
            name    => 'Success response parsed correctly',
            setup   => {
                xml_response_string => $self->_get_success_xml_response(),
            },
            result  => {
                return_hash => {
                    ActionNote          => 'Success',
                    MessageTime         => '2014-04-30T16:14:12+01:00',
                    SiteID              => 'CIMGBTest',
                    AirwayBillNumber    => '9150905632',
                    DHLRoutingCode      => 'GI:GIBGIB+48000001',
                    DHLRoutingDataId    => '2L',
                    ProductContentCode  => 'WPX',
                    ProductShortName    => 'EXPRESS WORLDWIDE',
                    ShipmentDate        => '2014-05-01',
                    BoxTrackingNumbers  => {
                        0 => 'JD014600000344879693',
                    },
                    OutputImage         => 'XlhBCl5GVDE3LDQxCl5BME4sLDMyCl5GREVYUFJFU1MgV09STERXSURFXkZTCl5GVDE2LDQxCl5BME4sLDMyCl5GREVYUFJFU1MgV09STERXSURFXkZTCl5GVDExMSw3MApeQTBOLCwxNQpeRkRYTUxQSSA1LjAgLyAqMDMtMTIxMSpeRlMKXkZPMzg2LDAKXkdCMTUwLDc5LDc5LEJeRlMKXkZUMzg4LDU1Cl5BME4sLDYyCl5GUl5GRFdQWF5GUwpeRk81NDMsMjMKXklNUjpkaGxsZzEuR1JGXkZTCl5GTzAsNzgKXkdCNzgwLDAsMixCXkZTCl5GVDE5LDEwMgpeQTBOLCwxNgpeRkRGcm9tIDpeRlMKXkZUMTksMTAyCl5BME4sLDE2Cl5GREZyb20gOl5GUwpeRlQ4NywxMDIKXkEwTiwsMjQKXkZETkVULUEtUE9SVEVSLkNPTV5GUwpeRlQ4NywxMjkKXkEwTiwsMjQKXkZERGlzcGF0Y2ggRGVwYXJ0bWVudF5GUwpeRlQ4NywxNTMKXkEwTiwsMjAKXkZEVW5pdCAzLCBDaGFybHRvbiBHYXRlIEJ1c2luZXNzIFBhcmteRlMKXkZUODcsMTgyCl5BME4sLDI0Cl5GRFNFNyA3UlUgTG9uZG9uXkZTCl5GVDg3LDIwOQpeQTBOLCwyNApeRkRVbml0ZWQgS2luZ2RvbV5GUwpeRlQ1MDgsMjA3Cl5BME4sLDE5Cl5GRENvbnRhY3Q6ICs0NCAoMCkgMjAgMzQ3MSA0NTEwXkZTCl5GVDY5MywxMDIKXkEwTiwsMjEKXkZET3JpZ2luOl5GUwpeRlQ2OTQsMTQwCl5BME4sLDM5Cl5GRExDWV5GUwpeRlQ2OTMsMTQwCl5BME4sLDM5Cl5GRExDWV5GUwpeRk8wLDIyMApeR0I3ODAsMCwyLEJeRlMKXkZUMzUsMjUyCl5BME4sLDE2Cl5GRFRvIDpeRlMKXkZUMzUsMjUyCl5BME4sLDE2Cl5GRFRvIDpeRlMKXkZPMjUsMjI2Cl5HQjAsMzEsNSxCXkZTCl5GTzI4LDIyNApeR0IzMSwwLDUsQl5GUwpeRk83NTAsMjI2Cl5HQjAsMzEsNSxCXkZTCl5GTzcyMCwyMjQKXkdCMzEsMCw1LEJeRlMKXkZPMjUsNDA5Cl5HQjAsMzEsNSxCXkZTCl5GTzI4LDQzOQpeR0IzMSwwLDUsQl5GUwpeRk83NTAsNDA5Cl5HQjAsMzEsNSxCXkZTCl5GTzcyMCw0MzkKXkdCMzEsMCw1LEJeRlMKXkZUODcsMjUyCl5BME4sLDMyCl5GRHNvbWUgb25lXkZTCl5GVDg3LDI5MQpeQTBOLCwzMgpeRkRzb21lIG9uZV5GUwpeRlQ4NywzMzAKXkEwTiwsMzIKXkZEMzIgLSAzNiBUb3duIFJhbmdlXkZTCl5GVDg3LDM3NwpeQTBOLCw0NApeRkRHaWJyYWx0YXJeRlMKXkZUODcsMzc3Cl5BME4sLDQ0Cl5GREdpYnJhbHRhcl5GUwpeRlQ4Nyw0MjkKXkEwTiwsNDQKXkZER2licmFsdGFyXkZTCl5GVDg3LDQyOQpeQTBOLCw0NApeRkRHaWJyYWx0YXJeRlMKXkZUNTc1LDI0NApeQTBOLCwxOQpeRkRDb250YWN0Ol5GUwpeRlQ1NzUsMjY0Cl5BME4sLDE5Cl5GRHRlbGVwaG9uZV5GUwpeRk8wLDQ0OApeR0I3ODAsMCwyLEJeRlMKXkZUOSw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRlQ4LDUwOApeQTBOLCw1MwpeRkQuXkZTCl5GVDE5NSw1MTMKXkEwTiwsNzIKXkZER0ktR0lCLUdJQl5GUwpeRlQxOTQsNTEzCl5BME4sLDcyCl5GREdJLUdJQi1HSUJeRlMKXkZUNzYxLDUwOApeQTBOLCw1MwpeRkQuXkZTCl5GVDc2MCw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRk8wLDUzNQpeR0I3ODAsMCwyLEJeRlMKXkZPMCw1MzUKXkdGQiwxOTIsMTkyLDMs//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8AAAAAXkZTCl5GTzE2LDUzNQpeR0I1NTEsNjMsNjMsQl5GUwpeRlQxOSw1NzgKXkEwTiwsNDYKXkZSXkZEQy1EVFBeRlMKXkZUNzAxLDU1MQpeQTBOLCwxNgpeRkRUaW1lXkZTCl5GVDYyNiw1NTEKXkEwTiwsMTYKXkZERGF5XkZTCl5GTzAsNTk4Cl5HQjc4MCwwLDIsQl5GUwpeRlQxMiw2MjIKXkEwTiwsMjEKXkZEUmVmOiAxMDAwMDAyMjI5XkZTCl5GVDQwMiw2MTcKXkEwTiwsMTYKXkZERGF0ZTpeRlMKXkZUNDAyLDYzOQpeQTBOLCwxOQpeRkQyMDE0LTA1LTAxXkZTCl5GVDUzNSw2MTcKXkEwTiwsMTYKXkZEUGNlL1NocHQgV2VpZ2h0XkZTCl5GVDUzNiw2NTMKXkEwTiwsMzcKXkZEMS4zIGtnXkZTCl5GVDUzNSw2NTMKXkEwTiwsMzcKXkZEMS4zIGtnXkZTCl5GVDcxMyw2MTcKXkEwTiwsMTYKXkZEUGllY2VeRlMKXkZUNzA1LDY1MwpeQTBOLCwzOQpeRkQxLzFeRlMKXkZUNzA1LDY1MwpeQTBOLCwzOQpeRkQxLzFeRlMKXkZPMCw3NDcKXkdCNzgwLDAsMixCXkZTCl5GTzUxLDc3NgpeQlkzLDIuNywyMDUKXkIzTixOLDIwNSxOLE4KXkZEOTE1MDkwNTYzMl5GUwpeRlQxODYsMTAwMwpeQTBOLCwyNQpeRkRXQVlCSUxMIDkxIDUwOTAgNTYzMl5GUwpeRlQ2NDIsNzk0Cl5BME4sLDE5Cl5GRENvbnRlbnRzIDpeRlMKXkZUNjQyLDgxNQpeQTBOLCwxOQpeRkRVbnNldCwgTm90IHJlc3ReRlMKXkZUNjQyLDgzNgpeQTBOLCwxOQpeRkRyaWN0ZWQgZm9yIHRyYW5eRlMKXkZUNjQyLDg1NwpeQTBOLCwxOQpeRkRzcG9ydF5GUwpeRk8xNjgsMTA4NwpeQlkyLDMuMCwyMDUKXkJDTiwyMDUsTixOLE4sQQpeRkQyTEdJOkdJQkdJQis0ODAwMDAwMV5GUwpeRlQyNzgsMTMxMgpeQTBOLCwxOQpeRkQoMkwpR0k6R0lCR0lCKzQ4MDAwMDAxXkZTCl5GTzEyMywxMzE5Cl5CWTMsMy4wLDIwNQpeQkNOLDIwNSxOLE4sTixBCl5GREpKRDAxNDYwMDAwMDM0NDg3OTY5M15GUwpeRlQyMTQsMTU0OApeQTBOLCwyNQpeRkQoSikgSkQwMSA0NjAwIDAwMDMgNDQ4NyA5NjkzXkZTCl5YWgpeWEEKXkZUNTQsMzcKXkEwTiwsMzMKXkZEKiBBUkNISVZFIERPQyAqXkZTCl5GVDUzLDM3Cl5BME4sLDMzCl5GRCogQVJDSElWRSBET0MgKl5GUwpeRlQ0NSw2OApeQTBOLCwyMQpeRkROb3QgdG8gYmUgYXR0YWNoZWQgdG8gcGFja2FnZV5GUwpeRk8zODYsMApeR0IxNTAsNzksNzksQl5GUwpeRlQzODgsNTUKXkEwTiwsNjIKXkZSXkZEV1BYXkZTCl5GTzU0MywyMwpeSU1SOmRobGxnMS5HUkZeRlMKXkZPMCw3OApeR0I3ODAsMCwyLEJeRlMKXkZUMjAsMTAyCl5BME4sLDE2Cl5GREZyb20gOl5GUwpeRlQyMCwxMDIKXkEwTiwsMTYKXkZERnJvbSA6XkZTCl5GVDg3LDEwMgpeQTBOLCwyNApeRkRORVQtQS1QT1JURVIuQ09NXkZTCl5GVDg3LDEyOQpeQTBOLCwyNApeRkREaXNwYXRjaCBEZXBhcnRtZW50XkZTCl5GVDg3LDE1MwpeQTBOLCwyMApeRkRVbml0IDMsIENoYXJsdG9uIEdhdGUgQnVzaW5lc3MgUGFya15GUwpeRlQ4NywxODIKXkEwTiwsMjQKXkZEU0U3IDdSVSBMb25kb25eRlMKXkZUODcsMjA5Cl5BME4sLDI0Cl5GRFVuaXRlZCBLaW5nZG9tXkZTCl5GVDUwOCwyMDcKXkEwTiwsMTkKXkZEQ29udGFjdDogKzQ0ICgwKSAyMCAzNDcxIDQ1MTBeRlMKXkZUNjkzLDEwMgpeQTBOLCwyMQpeRkRPcmlnaW46XkZTCl5GVDY5NCwxNDAKXkEwTiwsMzkKXkZETENZXkZTCl5GVDY5MywxNDAKXkEwTiwsMzkKXkZETENZXkZTCl5GTzAsMjIwCl5HQjc4MCwwLDIsQl5GUwpeRlQzNiwyNTIKXkEwTiwsMTYKXkZEVG8gOl5GUwpeRlQzNSwyNTIKXkEwTiwsMTYKXkZEVG8gOl5GUwpeRk8yNSwyMjYKXkdCMCwzMSw1LEJeRlMKXkZPMjgsMjI0Cl5HQjMxLDAsNSxCXkZTCl5GTzc1MCwyMjYKXkdCMCwzMSw1LEJeRlMKXkZPNzIwLDIyNApeR0IzMSwwLDUsQl5GUwpeRk8yNSw0MDkKXkdCMCwzMSw1LEJeRlMKXkZPMjgsNDM5Cl5HQjMxLDAsNSxCXkZTCl5GTzc1MCw0MDkKXkdCMCwzMSw1LEJeRlMKXkZPNzIwLDQzOQpeR0IzMSwwLDUsQl5GUwpeRlQ4NywyNTIKXkEwTiwsMzIKXkZEc29tZSBvbmVeRlMKXkZUODcsMjkxCl5BME4sLDMyCl5GRHNvbWUgb25lXkZTCl5GVDg3LDMzMApeQTBOLCwzMgpeRkQzMiAtIDM2IFRvd24gUmFuZ2VeRlMKXkZUODcsMzc3Cl5BME4sLDQ0Cl5GREdpYnJhbHRhcl5GUwpeRlQ4NywzNzcKXkEwTiwsNDQKXkZER2licmFsdGFyXkZTCl5GVDg3LDQyOQpeQTBOLCw0NApeRkRHaWJyYWx0YXJeRlMKXkZUODcsNDI5Cl5BME4sLDQ0Cl5GREdpYnJhbHRhcl5GUwpeRlQ1ODMsMjQ0Cl5BME4sLDE5Cl5GRENvbnRhY3Q6XkZTCl5GVDU4MywyNjQKXkEwTiwsMTkKXkZEdGVsZXBob25lXkZTCl5GTzAsNDQ4Cl5HQjc4MCwwLDIsQl5GUwpeRlQxNyw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRlQxNiw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRlQxOTUsNTEzCl5BME4sLDcyCl5GREdJLUdJQi1HSUJeRlMKXkZUMTk0LDUxMwpeQTBOLCw3MgpeRkRHSS1HSUItR0lCXkZTCl5GVDc1Myw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRlQ3NTIsNTA4Cl5BME4sLDUzCl5GRC5eRlMKXkZPMCw1MzUKXkdCNzgwLDAsMixCXkZTCl5GVDgsNTU3Cl5BME4sLDE5Cl5GRFByb2R1Y3Q6XkZTCl5GVDgsNTgyCl5BME4sLDI1Cl5GRFtQXSBFWFBSRVNTIFdPUkxEV0lERSAoNDgpXkZTCl5GVDgsNTgyCl5BME4sLDI1Cl5GRFtQXSBFWFBSRVNTIFdPUkxEV0lERSAoNDgpXkZTCl5GVDgsNjA0Cl5BME4sLDE5Cl5GRFBheW1lbnQgY29kZTpeRlMKXkZUOCw2MjQKXkEwTiwsMTkKXkZERlJUIEEvQzogMTM1MTA0NzE2XkZTCl5GVDgsNjQ0Cl5BME4sLDE5Cl5GRFRlcm1zIG9mIFRyYWRlOiBEVFBeRlMKXkZUOCw2NjMKXkEwTiwsMTkKXkZERFRQIEEvQzogMTM1MTA0NzE2XkZTCl5GVDQ0OSw1NTcKXkEwTiwsMTkKXkZERmVhdHVyZXMgLyBTZXJ2aWNlczpeRlMKXkZUNDQ5LDU3NApeQTBOLCwxNQpeRkQoREQpXkZTCl5GTzAsNjg0Cl5HQjc4MCwwLDIsQl5GUwpeRlQxMiw3MDQKXkEwTiwsMjEKXkZEUmVmOiAxMDAwMDAyMjI5XkZTCl5GVDEyLDc1MQpeQTBOLCwyMQpeRkRDdXN0b20gVmFsOiAxNjAuMDAgR0JQXkZTCl5GVDQzMyw3MDEKXkEwTiwsMTkKXkZEU2hwdCBXZ2h0Ol5GUwpeRlQ1MzIsNzE4Cl5BME4sLDM3Cl5GRDEuMyBrZ15GUwpeRlQ1MzEsNzE4Cl5BME4sLDM3Cl5GRDEuMyBrZ15GUwpeRlQzNzAsNzUxCl5BME4sLDIxCl5GRFNoaXBtZW50IERhdGU6XkZTCl5GVDUzMiw3NTEKXkEwTiwsMTkKXkZEMjAxNC0wNS0wMV5GUwpeRlQ1MzEsNzUxCl5BME4sLDE5Cl5GRDIwMTQtMDUtMDFeRlMKXkZUNjU5LDcwNApeQTBOLCwyMQpeRkQjIG9mIFBpZWNlc15GUwpeRlQ3NDQsNzQ0Cl5BME4sLDM5Cl5GRDFeRlMKXkZUNzQzLDc0NApeQTBOLCwzOQpeRkQxXkZTCl5GTzAsODU3Cl5HQjc4MCwwLDIsQl5GUwpeRk81MSw5MDIKXkJZMywyLjcsMjA1Cl5CM04sTiwyMDUsTixOCl5GRDkxNTA5MDU2MzJeRlMKXkZUMTc5LDExMjkKXkEwTiwsMjUKXkZEV0FZQklMTCA5MSA1MDkwIDU2MzJeRlMKXkZUNjQyLDkwNgpeQTBOLCwxOQpeRkRDb250ZW50cyA6XkZTCl5GVDY0Miw5MjcKXkEwTiwsMTkKXkZEVW5zZXQsIE5vdCByZXN0XkZTCl5GVDY0Miw5NDgKXkEwTiwsMTkKXkZEcmljdGVkIGZvciB0cmFuXkZTCl5GVDY0Miw5NjkKXkEwTiwsMTkKXkZEc3BvcnReRlMKXkZPMCwxMTQ5Cl5HQjc4MCwwLDIsQl5GUwpeRlQ4LDExNjcKXkEwTiwsMjEKXkZETGljZW5zZSBQbGF0ZXMgb2YgcGllY2VzIGluIHNoaXBtZW50XkZTCl5GVDgsMTE4NgpeQTBOLCwxOQpeRkRKRDAxNDYwMDAwMDM0NDg3OTY5M15GUwpeRlQzNTQsMTUyNgpeQTBOLCwxOQpeRkQtIHBhZ2UgMSBvZiAxIC1eRlMKXlhaCg==',
                },
            },
        },
        {
            name    => 'Ensure error response is parsed correctly',
            setup   => {
                xml_response_string => $self->_get_error_xml_response(),
            },
            result  => {
                return_hash => {
                    ActionNote  => 'Failed',
                    MessageTime => '2014-04-30T16:13:57+01:00',
                    SiteID      => 'CIMGBTest',
                    error       => {
                        42  => 'DHL can not be bothered to generate a label at this time',
                        # There exists a specific override in the production code for the
                        # description of error code 108. So this does not match the
                        # description in the raw XML response string
                        108 => 'DHL Service is unavailable, please contact Service Desk to get in touch with DHL to rectify the problem.'
                    },
                },
            },
        }
    ) {
        subtest $test->{name} => sub {
            my $return_data = XTracker::DHL::XMLDocument::parse_label_response_xml(
                $test->{setup}->{xml_response_string}
            );
            eq_or_diff($return_data, $test->{result}->{return_hash},
                'Return data is as expected');
        };
    }
}

sub _get_success_xml_response {
    return q{<?xml version="1.0" encoding="UTF-8"?><res:ShipmentResponse xmlns:res='http://www.dhl.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation= 'http://www.dhl.com ship-val-res.xsd'>
    <Response>
        <ServiceHeader>
            <MessageTime>2014-04-30T16:14:12+01:00</MessageTime>
            <MessageReference>1234567123456712345671234567</MessageReference>
            <SiteID>CIMGBTest</SiteID>
        </ServiceHeader>
    </Response>
    <Note>
        <ActionNote>Success</ActionNote>
    </Note>
    <AirwayBillNumber>9150905632</AirwayBillNumber>
    <ShipmentDate>2014-05-01</ShipmentDate>
    <DHLRoutingCode>GI:GIBGIB+48000001</DHLRoutingCode>
    <DHLRoutingDataId>2L</DHLRoutingDataId>
    <ProductContentCode>WPX</ProductContentCode>
    <ProductShortName>EXPRESS WORLDWIDE</ProductShortName>
    <InternalServiceCode>C</InternalServiceCode>
    <InternalServiceCode>DDP</InternalServiceCode>
    <Pieces>
        <Piece>
            <PieceNumber>1</PieceNumber>
            <Depth>43</Depth>
            <Width>34</Width>
            <Height>17</Height>
            <Weight>1.33</Weight>
            <PackageType>CP</PackageType>
            <DimWeight>4.970800</DimWeight>
            <DataIdentifier>J</DataIdentifier>
            <LicensePlate>JD014600000344879693</LicensePlate>
        </Piece>
    </Pieces>
    <LabelImage>
        <OutputFormat>ZPL2</OutputFormat>
        <OutputImage>XlhBCl5GVDE3LDQxCl5BME4sLDMyCl5GREVYUFJFU1MgV09STERXSURFXkZTCl5GVDE2LDQxCl5BME4sLDMyCl5GREVYUFJFU1MgV09STERXSURFXkZTCl5GVDExMSw3MApeQTBOLCwxNQpeRkRYTUxQSSA1LjAgLyAqMDMtMTIxMSpeRlMKXkZPMzg2LDAKXkdCMTUwLDc5LDc5LEJeRlMKXkZUMzg4LDU1Cl5BME4sLDYyCl5GUl5GRFdQWF5GUwpeRk81NDMsMjMKXklNUjpkaGxsZzEuR1JGXkZTCl5GTzAsNzgKXkdCNzgwLDAsMixCXkZTCl5GVDE5LDEwMgpeQTBOLCwxNgpeRkRGcm9tIDpeRlMKXkZUMTksMTAyCl5BME4sLDE2Cl5GREZyb20gOl5GUwpeRlQ4NywxMDIKXkEwTiwsMjQKXkZETkVULUEtUE9SVEVSLkNPTV5GUwpeRlQ4NywxMjkKXkEwTiwsMjQKXkZERGlzcGF0Y2ggRGVwYXJ0bWVudF5GUwpeRlQ4NywxNTMKXkEwTiwsMjAKXkZEVW5pdCAzLCBDaGFybHRvbiBHYXRlIEJ1c2luZXNzIFBhcmteRlMKXkZUODcsMTgyCl5BME4sLDI0Cl5GRFNFNyA3UlUgTG9uZG9uXkZTCl5GVDg3LDIwOQpeQTBOLCwyNApeRkRVbml0ZWQgS2luZ2RvbV5GUwpeRlQ1MDgsMjA3Cl5BME4sLDE5Cl5GRENvbnRhY3Q6ICs0NCAoMCkgMjAgMzQ3MSA0NTEwXkZTCl5GVDY5MywxMDIKXkEwTiwsMjEKXkZET3JpZ2luOl5GUwpeRlQ2OTQsMTQwCl5BME4sLDM5Cl5GRExDWV5GUwpeRlQ2OTMsMTQwCl5BME4sLDM5Cl5GRExDWV5GUwpeRk8wLDIyMApeR0I3ODAsMCwyLEJeRlMKXkZUMzUsMjUyCl5BME4sLDE2Cl5GRFRvIDpeRlMKXkZUMzUsMjUyCl5BME4sLDE2Cl5GRFRvIDpeRlMKXkZPMjUsMjI2Cl5HQjAsMzEsNSxCXkZTCl5GTzI4LDIyNApeR0IzMSwwLDUsQl5GUwpeRk83NTAsMjI2Cl5HQjAsMzEsNSxCXkZTCl5GTzcyMCwyMjQKXkdCMzEsMCw1LEJeRlMKXkZPMjUsNDA5Cl5HQjAsMzEsNSxCXkZTCl5GTzI4LDQzOQpeR0IzMSwwLDUsQl5GUwpeRk83NTAsNDA5Cl5HQjAsMzEsNSxCXkZTCl5GTzcyMCw0MzkKXkdCMzEsMCw1LEJeRlMKXkZUODcsMjUyCl5BME4sLDMyCl5GRHNvbWUgb25lXkZTCl5GVDg3LDI5MQpeQTBOLCwzMgpeRkRzb21lIG9uZV5GUwpeRlQ4NywzMzAKXkEwTiwsMzIKXkZEMzIgLSAzNiBUb3duIFJhbmdlXkZTCl5GVDg3LDM3NwpeQTBOLCw0NApeRkRHaWJyYWx0YXJeRlMKXkZUODcsMzc3Cl5BME4sLDQ0Cl5GREdpYnJhbHRhcl5GUwpeRlQ4Nyw0MjkKXkEwTiwsNDQKXkZER2licmFsdGFyXkZTCl5GVDg3LDQyOQpeQTBOLCw0NApeRkRHaWJyYWx0YXJeRlMKXkZUNTc1LDI0NApeQTBOLCwxOQpeRkRDb250YWN0Ol5GUwpeRlQ1NzUsMjY0Cl5BME4sLDE5Cl5GRHRlbGVwaG9uZV5GUwpeRk8wLDQ0OApeR0I3ODAsMCwyLEJeRlMKXkZUOSw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRlQ4LDUwOApeQTBOLCw1MwpeRkQuXkZTCl5GVDE5NSw1MTMKXkEwTiwsNzIKXkZER0ktR0lCLUdJQl5GUwpeRlQxOTQsNTEzCl5BME4sLDcyCl5GREdJLUdJQi1HSUJeRlMKXkZUNzYxLDUwOApeQTBOLCw1MwpeRkQuXkZTCl5GVDc2MCw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRk8wLDUzNQpeR0I3ODAsMCwyLEJeRlMKXkZPMCw1MzUKXkdGQiwxOTIsMTkyLDMs//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8A//8AAAAAXkZTCl5GTzE2LDUzNQpeR0I1NTEsNjMsNjMsQl5GUwpeRlQxOSw1NzgKXkEwTiwsNDYKXkZSXkZEQy1EVFBeRlMKXkZUNzAxLDU1MQpeQTBOLCwxNgpeRkRUaW1lXkZTCl5GVDYyNiw1NTEKXkEwTiwsMTYKXkZERGF5XkZTCl5GTzAsNTk4Cl5HQjc4MCwwLDIsQl5GUwpeRlQxMiw2MjIKXkEwTiwsMjEKXkZEUmVmOiAxMDAwMDAyMjI5XkZTCl5GVDQwMiw2MTcKXkEwTiwsMTYKXkZERGF0ZTpeRlMKXkZUNDAyLDYzOQpeQTBOLCwxOQpeRkQyMDE0LTA1LTAxXkZTCl5GVDUzNSw2MTcKXkEwTiwsMTYKXkZEUGNlL1NocHQgV2VpZ2h0XkZTCl5GVDUzNiw2NTMKXkEwTiwsMzcKXkZEMS4zIGtnXkZTCl5GVDUzNSw2NTMKXkEwTiwsMzcKXkZEMS4zIGtnXkZTCl5GVDcxMyw2MTcKXkEwTiwsMTYKXkZEUGllY2VeRlMKXkZUNzA1LDY1MwpeQTBOLCwzOQpeRkQxLzFeRlMKXkZUNzA1LDY1MwpeQTBOLCwzOQpeRkQxLzFeRlMKXkZPMCw3NDcKXkdCNzgwLDAsMixCXkZTCl5GTzUxLDc3NgpeQlkzLDIuNywyMDUKXkIzTixOLDIwNSxOLE4KXkZEOTE1MDkwNTYzMl5GUwpeRlQxODYsMTAwMwpeQTBOLCwyNQpeRkRXQVlCSUxMIDkxIDUwOTAgNTYzMl5GUwpeRlQ2NDIsNzk0Cl5BME4sLDE5Cl5GRENvbnRlbnRzIDpeRlMKXkZUNjQyLDgxNQpeQTBOLCwxOQpeRkRVbnNldCwgTm90IHJlc3ReRlMKXkZUNjQyLDgzNgpeQTBOLCwxOQpeRkRyaWN0ZWQgZm9yIHRyYW5eRlMKXkZUNjQyLDg1NwpeQTBOLCwxOQpeRkRzcG9ydF5GUwpeRk8xNjgsMTA4NwpeQlkyLDMuMCwyMDUKXkJDTiwyMDUsTixOLE4sQQpeRkQyTEdJOkdJQkdJQis0ODAwMDAwMV5GUwpeRlQyNzgsMTMxMgpeQTBOLCwxOQpeRkQoMkwpR0k6R0lCR0lCKzQ4MDAwMDAxXkZTCl5GTzEyMywxMzE5Cl5CWTMsMy4wLDIwNQpeQkNOLDIwNSxOLE4sTixBCl5GREpKRDAxNDYwMDAwMDM0NDg3OTY5M15GUwpeRlQyMTQsMTU0OApeQTBOLCwyNQpeRkQoSikgSkQwMSA0NjAwIDAwMDMgNDQ4NyA5NjkzXkZTCl5YWgpeWEEKXkZUNTQsMzcKXkEwTiwsMzMKXkZEKiBBUkNISVZFIERPQyAqXkZTCl5GVDUzLDM3Cl5BME4sLDMzCl5GRCogQVJDSElWRSBET0MgKl5GUwpeRlQ0NSw2OApeQTBOLCwyMQpeRkROb3QgdG8gYmUgYXR0YWNoZWQgdG8gcGFja2FnZV5GUwpeRk8zODYsMApeR0IxNTAsNzksNzksQl5GUwpeRlQzODgsNTUKXkEwTiwsNjIKXkZSXkZEV1BYXkZTCl5GTzU0MywyMwpeSU1SOmRobGxnMS5HUkZeRlMKXkZPMCw3OApeR0I3ODAsMCwyLEJeRlMKXkZUMjAsMTAyCl5BME4sLDE2Cl5GREZyb20gOl5GUwpeRlQyMCwxMDIKXkEwTiwsMTYKXkZERnJvbSA6XkZTCl5GVDg3LDEwMgpeQTBOLCwyNApeRkRORVQtQS1QT1JURVIuQ09NXkZTCl5GVDg3LDEyOQpeQTBOLCwyNApeRkREaXNwYXRjaCBEZXBhcnRtZW50XkZTCl5GVDg3LDE1MwpeQTBOLCwyMApeRkRVbml0IDMsIENoYXJsdG9uIEdhdGUgQnVzaW5lc3MgUGFya15GUwpeRlQ4NywxODIKXkEwTiwsMjQKXkZEU0U3IDdSVSBMb25kb25eRlMKXkZUODcsMjA5Cl5BME4sLDI0Cl5GRFVuaXRlZCBLaW5nZG9tXkZTCl5GVDUwOCwyMDcKXkEwTiwsMTkKXkZEQ29udGFjdDogKzQ0ICgwKSAyMCAzNDcxIDQ1MTBeRlMKXkZUNjkzLDEwMgpeQTBOLCwyMQpeRkRPcmlnaW46XkZTCl5GVDY5NCwxNDAKXkEwTiwsMzkKXkZETENZXkZTCl5GVDY5MywxNDAKXkEwTiwsMzkKXkZETENZXkZTCl5GTzAsMjIwCl5HQjc4MCwwLDIsQl5GUwpeRlQzNiwyNTIKXkEwTiwsMTYKXkZEVG8gOl5GUwpeRlQzNSwyNTIKXkEwTiwsMTYKXkZEVG8gOl5GUwpeRk8yNSwyMjYKXkdCMCwzMSw1LEJeRlMKXkZPMjgsMjI0Cl5HQjMxLDAsNSxCXkZTCl5GTzc1MCwyMjYKXkdCMCwzMSw1LEJeRlMKXkZPNzIwLDIyNApeR0IzMSwwLDUsQl5GUwpeRk8yNSw0MDkKXkdCMCwzMSw1LEJeRlMKXkZPMjgsNDM5Cl5HQjMxLDAsNSxCXkZTCl5GTzc1MCw0MDkKXkdCMCwzMSw1LEJeRlMKXkZPNzIwLDQzOQpeR0IzMSwwLDUsQl5GUwpeRlQ4NywyNTIKXkEwTiwsMzIKXkZEc29tZSBvbmVeRlMKXkZUODcsMjkxCl5BME4sLDMyCl5GRHNvbWUgb25lXkZTCl5GVDg3LDMzMApeQTBOLCwzMgpeRkQzMiAtIDM2IFRvd24gUmFuZ2VeRlMKXkZUODcsMzc3Cl5BME4sLDQ0Cl5GREdpYnJhbHRhcl5GUwpeRlQ4NywzNzcKXkEwTiwsNDQKXkZER2licmFsdGFyXkZTCl5GVDg3LDQyOQpeQTBOLCw0NApeRkRHaWJyYWx0YXJeRlMKXkZUODcsNDI5Cl5BME4sLDQ0Cl5GREdpYnJhbHRhcl5GUwpeRlQ1ODMsMjQ0Cl5BME4sLDE5Cl5GRENvbnRhY3Q6XkZTCl5GVDU4MywyNjQKXkEwTiwsMTkKXkZEdGVsZXBob25lXkZTCl5GTzAsNDQ4Cl5HQjc4MCwwLDIsQl5GUwpeRlQxNyw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRlQxNiw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRlQxOTUsNTEzCl5BME4sLDcyCl5GREdJLUdJQi1HSUJeRlMKXkZUMTk0LDUxMwpeQTBOLCw3MgpeRkRHSS1HSUItR0lCXkZTCl5GVDc1Myw1MDgKXkEwTiwsNTMKXkZELl5GUwpeRlQ3NTIsNTA4Cl5BME4sLDUzCl5GRC5eRlMKXkZPMCw1MzUKXkdCNzgwLDAsMixCXkZTCl5GVDgsNTU3Cl5BME4sLDE5Cl5GRFByb2R1Y3Q6XkZTCl5GVDgsNTgyCl5BME4sLDI1Cl5GRFtQXSBFWFBSRVNTIFdPUkxEV0lERSAoNDgpXkZTCl5GVDgsNTgyCl5BME4sLDI1Cl5GRFtQXSBFWFBSRVNTIFdPUkxEV0lERSAoNDgpXkZTCl5GVDgsNjA0Cl5BME4sLDE5Cl5GRFBheW1lbnQgY29kZTpeRlMKXkZUOCw2MjQKXkEwTiwsMTkKXkZERlJUIEEvQzogMTM1MTA0NzE2XkZTCl5GVDgsNjQ0Cl5BME4sLDE5Cl5GRFRlcm1zIG9mIFRyYWRlOiBEVFBeRlMKXkZUOCw2NjMKXkEwTiwsMTkKXkZERFRQIEEvQzogMTM1MTA0NzE2XkZTCl5GVDQ0OSw1NTcKXkEwTiwsMTkKXkZERmVhdHVyZXMgLyBTZXJ2aWNlczpeRlMKXkZUNDQ5LDU3NApeQTBOLCwxNQpeRkQoREQpXkZTCl5GTzAsNjg0Cl5HQjc4MCwwLDIsQl5GUwpeRlQxMiw3MDQKXkEwTiwsMjEKXkZEUmVmOiAxMDAwMDAyMjI5XkZTCl5GVDEyLDc1MQpeQTBOLCwyMQpeRkRDdXN0b20gVmFsOiAxNjAuMDAgR0JQXkZTCl5GVDQzMyw3MDEKXkEwTiwsMTkKXkZEU2hwdCBXZ2h0Ol5GUwpeRlQ1MzIsNzE4Cl5BME4sLDM3Cl5GRDEuMyBrZ15GUwpeRlQ1MzEsNzE4Cl5BME4sLDM3Cl5GRDEuMyBrZ15GUwpeRlQzNzAsNzUxCl5BME4sLDIxCl5GRFNoaXBtZW50IERhdGU6XkZTCl5GVDUzMiw3NTEKXkEwTiwsMTkKXkZEMjAxNC0wNS0wMV5GUwpeRlQ1MzEsNzUxCl5BME4sLDE5Cl5GRDIwMTQtMDUtMDFeRlMKXkZUNjU5LDcwNApeQTBOLCwyMQpeRkQjIG9mIFBpZWNlc15GUwpeRlQ3NDQsNzQ0Cl5BME4sLDM5Cl5GRDFeRlMKXkZUNzQzLDc0NApeQTBOLCwzOQpeRkQxXkZTCl5GTzAsODU3Cl5HQjc4MCwwLDIsQl5GUwpeRk81MSw5MDIKXkJZMywyLjcsMjA1Cl5CM04sTiwyMDUsTixOCl5GRDkxNTA5MDU2MzJeRlMKXkZUMTc5LDExMjkKXkEwTiwsMjUKXkZEV0FZQklMTCA5MSA1MDkwIDU2MzJeRlMKXkZUNjQyLDkwNgpeQTBOLCwxOQpeRkRDb250ZW50cyA6XkZTCl5GVDY0Miw5MjcKXkEwTiwsMTkKXkZEVW5zZXQsIE5vdCByZXN0XkZTCl5GVDY0Miw5NDgKXkEwTiwsMTkKXkZEcmljdGVkIGZvciB0cmFuXkZTCl5GVDY0Miw5NjkKXkEwTiwsMTkKXkZEc3BvcnReRlMKXkZPMCwxMTQ5Cl5HQjc4MCwwLDIsQl5GUwpeRlQ4LDExNjcKXkEwTiwsMjEKXkZETGljZW5zZSBQbGF0ZXMgb2YgcGllY2VzIGluIHNoaXBtZW50XkZTCl5GVDgsMTE4NgpeQTBOLCwxOQpeRkRKRDAxNDYwMDAwMDM0NDg3OTY5M15GUwpeRlQzNTQsMTUyNgpeQTBOLCwxOQpeRkQtIHBhZ2UgMSBvZiAxIC1eRlMKXlhaCg==</OutputImage>
    </LabelImage></res:ShipmentResponse>};
}

sub _get_error_xml_response {
    return q{<?xml version="1.0" encoding="UTF-8"?><res:ShipmentResponse xmlns:res='http://www.dhl.com' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:schemaLocation= 'http://www.dhl.com ship-val-res.xsd'>
    <Response>
        <ServiceHeader>
            <MessageTime>2014-04-30T16:13:57+01:00</MessageTime>
            <MessageReference>1234567123456712345671234567</MessageReference>
            <SiteID>CIMGBTest</SiteID>
        </ServiceHeader>
    </Response>
    <Note>
        <ActionNote>Failed</ActionNote>
    </Note>
    <Condition>
        <ConditionCode>42</ConditionCode>
        <ConditionData>DHL can not be bothered to generate a label at this time</ConditionData>
    </Condition>
    <Condition>
        <ConditionCode>108</ConditionCode>
        <ConditionData>wibble</ConditionData>
    </Condition></res:ShipmentResponse>};
}
