#!/bin/bash
GREP="${1:-.}"
find /var/log/nap/xt -name '*.log' -mtime -5 | \
xargs cat | \
grep -P "$GREP" | \
grep NAP::Messaging::Role::ConsumesJMS | \
grep time_taken | \
sort | \
perl -ne '/^([^|]+).+?{"(.+)/ and print qq/{"log_time": "$1","$2\n/' | \
perl -MJSON -ne '
$m = decode_json($_);
print join(
    "\t",
    map { s/fail-process/fail/r }
    map { ref($_) ? JSON->new->pretty->encode($_) : $_ }
    map { $m->{$_} }
    qw/ log_time result message_type message_content /
) . "\n"; '
