#!/bin/bash

# Work out dev db-name and user to use
DB_NAME="${SOS_DB_NAME}"
DB_USER="${SOS_DB_USER}"

# Drop existing db
psql -U postgres -c "DROP DATABASE IF EXISTS \"$DB_NAME\""
psql -U postgres -c "CREATE DATABASE \"$DB_NAME\" OWNER \"$DB_USER\""
./act "runMain nap.database.LiquibaseRunner"
# psql -U postgres sos < db/dbDumpJ.sql