Vagrant.configure(2) do |config|
  # Online documentation for this file available at https://docs.vagrantup.com.

  config.vm.box = "boxcutter/centos66"
  #config.vm.box_url = "http://pulp.wtf.nap/pulp/repos/vagrant/vagrant-centos-66-1427729137.box"

  config.vm.network "forwarded_port", guest: 9000, host: 9001
  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.network "forwarded_port", guest: 8161, host: 8161
  config.vm.network "forwarded_port", guest: 61616, host: 61616

  config.vm.provider "virtualbox" do |vb|
   vb.memory = "2048"
  end

  # TODO: Setup puppet (or something else) to do this for us
  config.vm.provision "shell", inline: <<-SHELL
    #cp /vagrant/vagrant-setup/repos/*.repo /etc/yum.repos.d/
    yum localinstall https://download.postgresql.org/pub/repos/yum/9.3/redhat/rhel-6-x86_64/pgdg-centos93-9.3-2.noarch.rpm
    yum clean all -y
    yum upgrade --nogpgcheck -y
    yum install postgresql93-server -y
    service postgresql-9.3 initdb
    cp /vagrant/vagrant-setup/pg_hba.conf /var/lib/pgsql/9.3/data/pg_hba.conf
    echo "listen_addresses = '*'" >> /var/lib/pgsql/9.3/data/postgresql.conf
    chkconfig --levels 235 postgresql-9.3 on
    service postgresql-9.3 start
    createuser -U postgres sos
    yum install postgresql93-jdbc --nogpgcheck -y
    yum install java-1.7.0-openjdk-devel --nogpgcheck -y
    yum install java-1.8.0-openjdk-devel --nogpgcheck -y
    update-alternatives --set java /usr/lib/jvm/java-1.8.0-openjdk.x86_64/bin/java
    yum install mlocate -y --nogpgcheck
    yum install liquibase --nogpgcheck -y
    yum install rpm-build -y --nogpgcheck
    yum install activemq -y --nogpgcheck
    service activemq start
    service iptables stop
    chkconfig iptables off
    chkconfig iptables --del

    # Need these for db_refresh script
    export SOS_DB_NAME=sos
    export SOS_DB_USER=sos
    echo "export SOS_DB_NAME=$SOS_DB_NAME" >> /home/vagrant/.bashrc
    echo "export SOS_DB_USER=$SOS_DB_USER" >> /home/vagrant/.bashrc

    # Need this as else system can not identify it's own hostname as itself (liquibase)
    echo "127.0.0.1 centos66" >> /etc/hosts
    cd /vagrant/
    ./db/refresh_db
    ./activator clean stage
  SHELL
end

