#!/opt/xt/xt-perl/bin/perl

use strict;
use warnings;

=head1 NAME

script/housekeeping/web_xt_consistency/pws_reservations_adjustment

=head1 DESCRIPTION

Compare reservations in XT and the websites and fix any on the website that
don't match.

It accepts -v for verbose output.

=head1 SYNOPSIS

    perl script/housekeeping/web_xt_consistency/pws_reservations_adjustment -v

=cut

use FindBin::libs;
use FindBin::libs qw( base=lib_dynamic );
use Getopt::Long;

use XTracker::Script::Consistency::PWSReservationsAdjustment;

my %opt = (
    help => 0,
    verbose => 0,
);

my $result = GetOptions( \%opt,
    'verbose|v',
    'help|h|?',
);

pod2usage(1) if (!$result || $opt{help});

XTracker::Script::Consistency::PWSReservationsAdjustment->new->invoke(%opt);
