#!/usr/bin/perl
use strict;
use warnings;
use FindBin::libs;

use Test::Most;
use Test::XTracker::Data;    # preloading
use SchemaTest;

use XTracker::Constants::FromDB qw( :shipment_type :shipment_class );

my $schematest = SchemaTest->new(
    {
        dsn_from  => 'xtracker',
        namespace => 'XTracker::Schema',
        moniker   => 'Public::Shipment',
        glue      => 'Result',
    }
);
$schematest->methods(
    {
        columns => [
            qw[
                id
                date
                shipment_type_id
                shipment_class_id
                shipment_status_id
                shipment_address_id
                gift
                gift_message
                outward_airway_bill
                return_airway_bill
                email
                telephone
                mobile_telephone
                packing_instruction
                shipping_charge
                comment
                delivered
                gift_credit
                store_credit
                legacy_shipment_nr
                destination_code
                shipping_charge_id
                shipping_account_id
                premier_routing_id
                real_time_carrier_booking
                av_quality_rating
                sla_priority
                sla_cutoff
                has_packing_started
                packing_other_info
                signature_required
                nominated_delivery_date
                nominated_dispatch_time
                nominated_earliest_selection_time
                last_updated
                is_picking_commenced
                is_prioritised
                wms_initial_pick_priority
                wms_deadline
                wms_bump_pick_priority
                wms_bump_deadline
                has_valid_address
                force_manual_booking
            ]
        ],

        relations => [
            qw[
                allocations
                link_delivery__shipments
                link_manifest__shipments
                link_orders__shipments
                link_shipment__promotion
                link_stock_transfer__shipments
                log_shipment_rtcb_states
                renumerations
                returns
                shipment_address
                shipping_account
                shipment_boxes
                shipment_email_logs
                shipment_internal_email_logs
                shipment_extra_items
                shipment_flags
                shipment_holds
                shipment_items
                shipment_notes
                shipment_print_logs
                shipment_class
                shipment_status
                shipment_type
                shipping_charge_table
                link_orders__shipment
                link_return_arrival__shipments
                link_order__shipment
                link_routing_export__shipments
                link_stock_transfer__shipment
                shipment_status_logs
                premier_routing
                return
                orders
                manifests
                log_shipment_signature_requireds
                routing_schedules
                link_routing_schedule__shipments
                shipment_message_logs
                link_sms_correspondence__shipments
                shipment_address_logs
                exchange_return
                shipment_hold_logs
                shipment_items_ij
                link_orders__shipment_ij
                credit_logs
            ]
        ],

        custom => [
            qw[
                is_standard_class
                is_press_class
                is_sample_shipment
                is_sample_class
                is_replacement_class
                is_transfer_shipment
                is_exchange
                is_premier
                is_domestic
                unselected_items
                selected_items
                picked_items
                unpicked_items
                non_canceled_items
                active_items
                canceled_items
                is_multi_item
                get_picked_items_by_container
                is_awaiting_return
                is_active
                is_on_return_hold
                is_cancelled
                is_dispatched
                is_on_exchange_hold
                is_lost
                packing_exception_items
                qc_failed_items
                missing_items
                is_at_packing_exception
                has_packing_exception_items
                is_packing_exception_completed
                charge_class
                is_carrier_automated
                in_premier_area
                update_status
                cancel
                set_cancelled
                set_lost
                clear_carrier_automation_data
                customer_details
                shipper_details
                carrier
                variants
                order
                stock_transfer
                get_channel
                stock_status_for_iws
                dispatched_date
                return_cutoff_date
                tracking_uri
                return_item_from_primary_return
                list_picking_print_docs
                picking_print_docs_info
                picking_print_doc_info
                address_card_printed
                generate_return_proforma
                calculate_shipping
                total_tax
                total_price
                total_duty
                get_conversion_rate_to
                total_weight
                get_sales_invoice
                get_invoices
                payment_renumerations
                refund_renumerations
                apply_SLAs
                get_sla_cutoff
                get_sla_priority
                is_pick_complete
                get_total_spent_by_card
                get_total_spent_by_store_credit
                get_store_credit_refund
                get_card_refund
                is_shipment_packed
                list_class
                count_sale_items
                is_first_order
                is_sale_order
                is_staff_order
                check_and_release_dates
                fulfilment_or_shipping_notes
                is_shipment_completely_packed
                is_shipment_completely_picked
                is_virtual_voucher_only
                dispatch_virtual_voucher_only_shipment
                auto_pick_virtual_vouchers
                summarise_gift_message
                has_vouchers
                print_sticker
                stickers_enabled
                stickers_printed
                container_ids
                packable_container_ids
                containers
                has_containers
                pack_status
                items_by_sku
                qc_fail_shipment_extra_item
                qc_fix_shipment_extra_item
                fix_shipment_items_exception
                is_awaiting_replacements
                is_being_replaced
                send_to_commissioner
                is_held
                is_on_hold
                is_ddu_pending
                is_on_preorder
                is_processing
                is_on_finance_hold
                relationships_for_signature
                iws_stock_status
                iws_priority_class
                does_iws_know_about_me
                has_validated_address
                ups_quality_rating_threshold
                can_be_put_on_hold
                can_be_put_on_finance_hold
                put_on_hold
                set_on_hold
                can_be_released_from_hold
                release_from_hold
                hold_if_invalid
                is_pigeonhole_only
                has_pigeonhole_items
                change_status_to
                set_status_processing
                set_status_finance_hold
                has_same_address_as_billing_address
                count_address_in_uncancelled
                shipment_type_for_packing
                is_voucher_only
                is_on_ddu_hold
                is_signature_required
                update_signature_required
                can_edit_signature_flag
                invoice_address
                branded_salutation
                set_status_hold
                has_routing_exports
                has_manifests
                send_routing_schedule_notification
                can_use_csm
                csm_prefs_allow_method
                get_return_correspondence_logs
                get_phone_number
                premier_mobile_number_for_SMS
                set_carrier_automated
                assign_boxes
                is_saturday_nominated_delivery_date
                has_hazmat_items
                pre_order_create_cancellation_card_refund
                get_item_shipping_attributes
                can_have_in_the_box_promotions
                get_promotion_types_for_invoice
                is_on_hold_for_invalid_address_chars
                clear_invalid_address_shipment_hold_records
                validate_address
                nap_carrier
                get_from_address_data
                can_be_carrier_automated
                log_internal_email
                update_status_based_on_third_party_psp_payment_status
                validate_address_change_with_psp
                should_notify_psp_when_basket_changes
                notify_psp_of_item_changes
                get_payment_info_for_tt
                count_items_of_product_types
                has_items_of_product_types
                has_only_items_of_product_types
                send_hold_update
                send_release_update
                send_status_update
                can_send_shipment_status_updates
                contains_on_sale_items
                hold_if_invalid_address_characters
                calculate_shipping_tax
                get_shipment_basket
                get_shipment_basket_instance
                notify_psp_of_basket_changes_or_cancel_payment
                should_cancel_payment_after_forced_address_update
            ],
            # from Role 'Schema::Role::CustomerHierarchy'
            qw[
                next_in_hierarchy
                next_in_hierarchy_isa
                next_in_hierarchy_from_class
                next_in_hierarchy_with_method
            ]
        ],

        resultsets => [
            qw[
                hold_status_list
                packing_summary
                invalid_shipments
                container_ids
                containers
                nominated_day_possible_sla_breach
                nominated_day_sla_breach
                nominated_day_shipments_summary
                premier
                non_premier
                nominated_day_status_count_for_day
                nominated_to_dispatch_on_day
                get_transfer_selection_list
                get_order_selection_list
                get_selection_list
                not_cancelled
                get_historic_min_shipment_id
                get_shipments_for_variant_id
                get_shipment_ids_for_variant_id
            ]
        ],
    }
);

$schematest->run_tests();
