#!/bin/env perl
# vim: ts=8 sts=4 et sw=4 sr sta
use strict;
use warnings;
BEGIN {
    use FindBin qw($Bin);
    use lib "$Bin/../lib";
use FindBin::libs qw( base=lib_dynamic );
}
use XTracker::BuildConstants;

my $builder = XTracker::BuildConstants->new;
$builder->prepare_constants();
$builder->spit_out_template();

