#!/opt/xt/xt-perl/bin/perl

use strict;
use warnings;
use Data::Dump  qw( pp );
use FindBin;

use lib qq{$FindBin::RealBin/../lib};
use FindBin::libs qw( base=lib_dynamic );


use XTracker::DHL::XMLDocument;
use XTracker::DHL::XMLRequest;

    my $data            = undef;
    my $xml_request     = undef;
    my $xml_response    = undef;

my $xmlpi_info = {
    address     => 'xmlpi-ea.dhl.com',
    username    => 'NetAPorter',
    password    => 'WrIephi8qo',
};

#<Address1>Nassaulaan 9F</Address1>
#<Address2></Address2>
#<Address3></Address3>
#<PostalCode>2011 PB</PostalCode>
#<City>Haarlem</City>
#<Division>O</Division>
#<CountryCode>NL</CountryCode>
#<CountryName>Netherlands</CountryName> 
#<?xml version="1.0" encoding="UTF-8"?>
#<req:RoutingRequestEA xmlns:req="http://www.dhl.com">
#    <Request>
#        <ServiceHeader>
#            <MessageTime>2010-04-19T16:18:00.000-00:00</MessageTime>
#<MessageReference>1222333444566677777778888899999</MessageReference>
#            <SiteID>NetAPorter</SiteID>
#            <Password>WrIephi8qo</Password>
#        </ServiceHeader>
#    </Request>
#    <RequestType>D</RequestType>
#    <Address1>THE FORGE, LANGFORD ROAD,</Address1>
#    <Address2>LOWER LANGFORD</Address2>
#    <Address3></Address3>
#    <PostalCode>BS40 5HU</PostalCode>
#    <City>BRISTOL</City>
#    <Division>O</Division>
#    <CountryCode>GB</CountryCode>
#    <CountryName>United Kingdom</CountryName>
#    <OriginCountryCode>GB</OriginCountryCode>
#</req:RoutingRequestEA>


$xml_request = XTracker::DHL::XMLDocument::build_routing_xml({
    address         => "xmlpi-ea.dhl.com",
    password        => "WrIephi8qo",
    username        => "NetAPorter",
    date            => "2006-01-01T01:00:00.000-00:00",

#    address_line_1  => "123 Acatia Avenue",
#    address_line_2  => "a2",
#    postcode        => "2011 PB",
#    country_code    => "GB",
#    country         => "United Kingdom",


#    address_line_1  => "Nassaulaan 9F",
#    address_line_2  => "",
#    postcode        => "2011 PB",
#    country_code    => "NL",
#    country         => "Netherlands",

    address_line_1  => "THE FORGE, LANGFORD ROAD,",
    address_line_2  => "LOWER LANGFORD",
    postcode        => "BS40 5HU",
    towncity        => "BRISTOL",
    country_code    => "GB",
    country         => "United Kingdom",

 

});

eval {
    $xml_response = XTracker::DHL::XMLRequest::send_xml_request(
        $xmlpi_info->{address},
        $xml_request
    );

};

if ($@) {
    die "ERROR: $@";
}

eval {
    $data = XTracker::DHL::XMLDocument::parse_routing_response(
        $xml_response
    );
};

if ($@) {
    warn __PACKAGE__ .": parse_routing_response failed - ". $@;
}

print pp($data);
