#!/bin/bash
#
# Startup script for TheSchwartz Job queue, called from jobqueuectl
# This script calls the job_queue_worker script which in turn recalls this script again
# to launch each of the worker groups using the daemon tools functionality.
#

# Source function library.
. /etc/rc.d/init.d/functions
RUNAS=${RUNAS_JOBQUEUE:xt-jq}
PN=`basename $0`

# Set the umask for group write permissions
UMASK=002
umask $UMASK

# Define startup log and create it if necessary
STARTUPLOG="$XTDC_LOGS_DIR/jobqueue_startup.log"
if [ ! -f $STARTUPLOG ]; then
    # Do it this way to avoid sudo applying its own 022 mask
    sudo -u $RUNAS sh -c "umask $UMASK && touch $STARTUPLOG"
fi

help() {
    echo "$PN --worker-group=[ALL|workgroup] start|stop|restart"
}

WORKER_GROUP="";
USERSET=0;

ARGS=`getopt --name "$PN" --long worker-group:,no-daemon,userset:: --options w:n:u -- "$@"`
if [ $? -ne 0 ]; then
    exit 1
    help
fi
eval set -- $ARGS

while [ $# -gt 0 ]; do
    case "$1" in
        -w | --worker-group)
            WORKER_GROUP="$2";
            shift;;
        -u | --userset)
            USERSET=1;
            shift;;
        --)
            shift;
            break;;
    esac
    shift
done

if [ -n "$WORKER_GROUP" ]; then

    if [ $# -gt 0 ]; then

        case "$1" in
            start)
                if [ "$WORKER_GROUP" == "ALL" ] ; then
                    echo "Starting all Job Queues..." > $STARTUPLOG
                    sudo -Eu $RUNAS $XTDC_BASE_DIR/script/job_queue_worker --worker-group=ALL $@
                else
                    if [ $USERSET == 1 ] ; then
                        echo -e "\nStarting Job Queue Daemon for $WORKER_GROUP" >> $STARTUPLOG
                        daemon $XTDC_BASE_DIR/script/job_queue_worker --worker-group=$WORKER_GROUP --no-daemon $@ </dev/null >> $STARTUPLOG 2>&1 \&
                    else
                        echo -e "\nStarting Job Queue Daemon (as $RUNAS) for $WORKER_GROUP" >> $STARTUPLOG
                        daemon --user $RUNAS $XTDC_BASE_DIR/script/job_queue_worker --worker-group=$WORKER_GROUP --no-daemon $@ </dev/null >> $STARTUPLOG 2>&1 \&
                    fi
                fi
                ;;
            stop)
                if [ "$WORKER_GROUP" == "ALL" ] ; then
                    sudo -Eu $RUNAS $XTDC_BASE_DIR/script/job_queue_worker --worker-group=ALL $@
                else
                    $XTDC_BASE_DIR/script/job_queue_worker --worker-group=$WORKER_GROUP $@
                fi
                ;;
            restart)
                if [ "$WORKER_GROUP" == "ALL" ] ; then
                    sudo -Eu $RUNAS $XTDC_BASE_DIR/script/job_queue_worker --worker-group=ALL stop
                    sudo -Eu $RUNAS $XTDC_BASE_DIR/script/job_queue_worker --worker-group=ALL start
                else
                    $XTDC_BASE_DIR/script/job_queue_worker --worker-group=$WORKER_GROUP stop
                    $XTDC_BASE_DIR/script/job_queue_worker --worker-group=$WORKER_GROUP start
                fi
                ;;
            *)
                help
                exit 1
        esac
    else
        help
    fi

else
    help
fi
