#!/opt/xt/xt-perl/bin/perl

use NAP::policy;

use FindBin::libs;
use FindBin::libs qw( base=lib_dynamic );
use Getopt::Long;
use Pod::Usage;
use XTracker::Printers::Populator;

=head1 NAME

populate_printers - Repopulate printers if config has changed

=head1 SYNOPSIS

    populate_printers [-q]

=head1 OPTIONS

=over

=item quiet|q

No output

=item help|h

This screen

=back

=cut

my $result = GetOptions( 'quiet|q' => \(my $quiet), 'help|h' => \(my $help), );

pod2usage(1) if !$result || $help;

my $xpp = XTracker::Printers::Populator->new;

unless ( $xpp->has_config_changed ) {
    $quiet || say q{Printer config hasn't changed, won't repopulate printers};
    exit(0)
}

$quiet || say 'Printer config has changed, repopulating printers';
$xpp->populate_if_updated;

$quiet || say 'Done';
exit(0);
