#!/opt/xt/xt-perl/bin/perl
use NAP::policy "tt";
use FindBin::libs;
use FindBin::libs qw( base=lib_dynamic );
use Getopt::Long;

use XTracker::Config::Local;
use XTracker::Database qw/schema_handle/;
use XTracker::Role::WithAMQMessageFactory;

my $use_num = 0;
my $use_id = 0;

$|++;

GetOptions(
    'order_nr'      => \$use_num,
    'order_id'      => \$use_id,
);

if ($use_num and $use_id) {
    print "  You can only have one of --order_nr or --order_id\n\n";
    exit;
}

if (not ($use_num or $use_id)) {
    print "  Specify either --order_nr or --order_id\n\n";
    exit;
}

my $field = ($use_id) ?  'order_id' : 'order_nr';

my $schema = schema_handle();

my $factory = XTracker::Role::WithAMQMessageFactory->build_msg_factory;

$factory->transformer_args->{schema} = $schema;

foreach my $order (@ARGV) {
    print "Sending message for $order\n";
    eval {
        $factory->transform_and_send(
            'XT::DC::Messaging::Producer::Orders::Update',
            { $field => $order }
        );
    };
    if ( my $error = $@ ) {
        chomp( $error );
        print "    Error: ${error}\n";
    }
}
