#!/opt/xt/xt-perl/bin/perl

use strict;
use warnings;
use lib qw( /opt/xt/deploy/xtracker/lib );
use FindBin::libs qw( base=lib_dynamic );
use XTracker::Database qw( get_database_handle);
use XT::JQ::DC;

my $debug = $ENV{'DEBUG'};

my $dbh = get_database_handle( { name => 'xtracker', type => 'readonly' });

my $job = XT::JQ::DC->new({ funcname => 'Send::Product::StockSummary' });
my @payload;

my $qry = "select * from product.stock_summary where last_updated > current_timestamp - interval '20 minutes'";
my $sth = $dbh->prepare($qry);
$sth->execute();
while ( my $row = $sth->fetchrow_hashref ) {

        my %record;

        print "$row->{product_id}\n" if $debug;

        foreach my $field ( keys %{$row} ){
            print "$field = $row->{$field}\n" if $debug;
            $record{$field} = $row->{$field};
        }

        push @payload, \%record;
}

my $got_payload = @payload;

if ($got_payload > 0){
        print "Creating job...\n" if $debug;
        $job->set_payload( \@payload );
        $job->send_job();

}
else {
        print "Job skipped due no payload\n" if $debug;
}
