#!/bin/sh

# Generated at Mon Sep 22 14:44:21 2014 with Daemon::Control 0.001006

### BEGIN INIT INFO
# Provides:          XT AMQ consumer application
# Required-Start:    $local_fs $remote_fs $network $named
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop XT AMQ consumer
# Description:       XT AMQ consumer application
### END INIT INFO`

# We need to make sure we change the current working directory to a world
# readable location. If the current directory wasn't readable by the $runas
# user, then loading modules by iterating through @INC would fail when trying
# to read ('.')
cd '/'

if [ -x /opt/xt/deploy/xtracker/script/xt_activemq_dc_server.pl ];
then
    /opt/xt/deploy/xtracker/script/xt_activemq_dc_server.pl $1
else
    echo "Required program /opt/xt/deploy/xtracker/script/xt_activemq_dc_server.pl not found!"
    exit 1;
fi
