-- SHIP-420
-- DC3
-- add 'Sydney and Melbourne Next Business Day' shipping charge
-- 287 postcodes, shipping copy and country price override

BEGIN;

-- Create shipping_charge entry
insert into shipping_charge (
    sku,
    description,
    charge,
    currency_id,
    flat_rate,
    class_id,
    channel_id,
    is_enabled,
    is_express,
    is_slow
)
values (
    '9000330-001',
    'Sydney and Melbourne Next Business Day',
    13.64, -- exc. VAT
    (select id from currency where currency = 'AUD'),
    True, -- is flat_rate
    (select id from shipping_charge_class where class = 'Air'),
    (select id from channel where web_name ilike 'NAP%'),
    False, -- is_enabled (it's not - will be enabled after copy/translations)
    True, -- is_express (it is)
    False -- is_slow (it's not)
);

-- Add country charge override
insert into shipping.country_charge (
    shipping_charge_id,
    country_id,
    currency_id,
    charge
)
values(
    (select id from shipping_charge where sku = '9000330-001'),
    (select id from country where code = 'AU'),
    (select id from currency where currency = 'AUD'),
    15.00 -- inc VAT. Yes, that's how it works.
);

-- Add shipping copy
insert into shipping.description
values
(
    'Next Business Day', -- name
    'Next Business Day', -- public_name
    'Next Business Day', -- title
    'Next Business Day', -- public_title
    'Order by 1.30pm, Mon-Fri',
    '&bull;  Delivery between 9am-5pm, Monday to Friday <br />&bull;  Orders placed before 1.30pm Monday to Friday will be delivered next business day <br  />&bull; Orders placed after 1.30pm on Friday will be delivered on Tuesday',
    'Delivery: next business day, 9am-5pm, Mon-Fri',
    'You will receive an email confirming the dispatch of your order and your Air Waybill number.',
    (select id from shipping_charge where sku = '9000330-001')  -- Shipping charge id
);

-- This shipping option is only available to these postcodes...
-- (287 of them, FYI)
insert into postcode_shipping_charge (postcode, country_id, shipping_charge_id, channel_id)
values
    ('2000', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2006', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2007', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2008', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2009', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2010', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2011', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2012', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2015', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2016', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2017', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2018', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2019', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2020', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2021', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2022', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2023', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2024', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2025', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2026', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2027', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2028', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2029', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2030', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2031', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2031', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2032', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2033', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2034', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2035', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2036', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2037', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2038', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2040', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2041', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2042', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2043', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2044', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2046', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2047', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2048', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2049', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2050', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2052', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2060', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2061', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2062', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2063', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2064', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2065', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2066', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2067', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2068', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2069', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2070', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2071', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2072', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2073', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2074', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2075', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2076', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2085', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2086', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2088', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2089', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2090', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2092', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2093', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2095', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2096', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2097', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2099', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2100', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2101', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2102', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2103', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2106', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2107', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2109', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2110', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2111', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2112', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2113', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2114', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2115', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2116', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2117', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2118', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2119', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2124', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2125', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2126', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2127', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2128', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2130', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2131', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2134', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2135', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2136', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2137', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2138', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2140', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2141', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2142', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2143', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2144', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2145', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2146', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2147', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2148', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2150', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2151', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2152', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2153', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2154', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2155', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2160', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2161', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2162', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2163', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2164', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2165', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2190', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2191', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2192', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2193', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2194', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2195', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2196', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2197', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2198', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2199', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2200', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2203', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2204', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2205', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2206', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2207', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2208', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2209', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2210', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2211', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2212', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2214', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2216', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2226', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2227', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2228', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2751', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2760', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2766', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('2767', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3000', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3001', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3002', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3003', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3004', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3006', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3008', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3011', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3012', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3013', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3015', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3016', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3018', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3019', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3020', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3022', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3026', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3031', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3032', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3033', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3034', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3039', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3040', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3041', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3042', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3043', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3044', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3045', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3046', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3047', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3048', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3051', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3052', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3053', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3054', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3055', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3056', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3057', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3058', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3060', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3061', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3062', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3065', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3066', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3067', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3068', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3070', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3071', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3072', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3073', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3074', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3075', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3078', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3079', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3081', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3082', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3083', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3084', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3085', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3087', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3101', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3104', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3106', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3107', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3108', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3109', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3116', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3121', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3122', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3123', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3124', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3125', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3126', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3127', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3128', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3129', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3130', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3131', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3132', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3133', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3134', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3135', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3136', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3137', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3138', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3141', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3142', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3143', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3144', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3145', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3146', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3147', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3148', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3149', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3150', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3151', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3152', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3153', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3155', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3162', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3163', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3165', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3166', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3167', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3168', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3169', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3170', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3171', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3172', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3173', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3174', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3177', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3178', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3179', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3180', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3181', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3182', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3183', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3184', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3185', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3186', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3188', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3189', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3190', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3191', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3192', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3193', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3194', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3202', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3204', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3205', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3206', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3207', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3800', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%')),
    ('3803', (SELECT id FROM country WHERE code = 'AU'), (SELECT id FROM shipping_charge WHERE sku = '9000330-001'), (SELECT id FROM channel WHERE web_name ilike 'NAP%'));

COMMIT;
