#!/usr/bin/env bash
DC1_HOST=dc1ca
DC2_HOST=dc2ca

#let ${DC1_HOST}_REV=42895
#let ${DC2_HOST}_REV=42948

DC_ROOT_ORIGIN=$HOME/development/xt
DC_ROOT_DESTINY=/opt/xt/deploy/xtracker-ci-root
DC_CONF_DIR=/opt/xt/local-conf/
XT_PERL=/opt/xt/xt-perl/bin/perl

# make sure we're up to date
#(cd $DC_ROOT_ORIGIN && xsvk up -s)
# just do this for now as we are now using git
(cd $DC_ROOT_ORIGIN)

for box in $DC1_HOST $DC2_HOST; do
    echo "[$box]";

    ssh ${box} "/etc/init.d/xt stop" &
    ssh ${box} "sudo -u nobody ${DC_ROOT_DESTINY}/script/job_queue_worker stop" &
    ssh ${box} "/etc/init.d/ntpd stop" &
    ssh ${box} "ntpdate 192.168.30.8" &
    ssh ${box} "/etc/init.d/ntpd start" &

    echo "[rsync -av -P --stats --delete ${DC_ROOT_ORIGIN}/ ${box}:${DC_ROOT_DESTINY}/]"
    rsync -av -P --stats --delete ${DC_ROOT_ORIGIN}/ ${box}:${DC_ROOT_DESTINY}/;
    wait;
    ssh ${box} "$XT_PERL /root/CI/sources/generate_config.pl -s /root/CI/sources/CI-configs.conf -c /opt/xt/deploy/xtracker/../env-conf/intl_ci/xtracker.conf.tt -t CIdc2ca"
    ssh ${box} "$XT_PERL /root/CI/sources/generate_config.pl -s /root/CI/sources/CI-configs.conf -c /opt/xt/deploy/xtracker/../env-conf/am_ci/xtracker.conf.tt -t CIdc2ca"
    ssh ${box} "${DC_ROOT_DESTINY}/script/build_constants > ${DC_ROOT_DESTINY}/lib/XTracker/Constants/FromDB.pm" &
    ssh ${box} chown -R nobody.nobody /opt/xt/deploy/{xtracker,xt-trunk*};
    ssh ${box} "sudo -u nobody ${DC_ROOT_DESTINY}/script/job_queue_worker" &

    ssh ${box} /etc/init.d/xt start;
    #echo "[Giving servers a chance to start-up]" && sleep 10;
    FOOTER_VERSION=`elinks -dump http://${box}/ |grep "NET-A-PORTER"`
    echo "[http://$box/ is running $FOOTER_VERSION]";
done


echo "DONE";
