#!/bin/bash -
#
# run the export script, and put its output somewhere useful
#
# label the output we generate to allow us to trace it back
# to a particular time and data, if required
#

RECON_HOME=${XT_RECON_HOME:-script/iws_reconciliation}
RECON_WORK_DIR=$RECON_HOME/var
RECON_BIN_DIR=$RECON_HOME

function die() {
    estat=${1:-3}
    err=${2:-'BUG -- no error message provided'}

    echo "$(basename $0): $err" >&2
    exit "$estat"
}

if [ X != "X$XTDC_BASE_DIR" ]
then
    cd "$XTDC_BASE_DIR"
fi

if [ X != "X$DB_HOST" ]
then
    db_host=$DB_HOST
else
    # we don't default db_host, because you should know what you
    # want to export from

    db_host=$1;  shift
fi

if [ X != "X$DB_NAME" ]
then
    db_name=$DB_NAME
else
    case "$db_host" in
    xtdc1*) db_name=${db_name:-xtracker}     ;;
    xtdc2*) db_name=${db_name:-xtracker_dc2} ;;
    esac
fi

if [ X != "X$DB_USER" ]
then
    db_user=$DB_USER
else
    db_user=postgres
fi

[ $# -ge 1 ] || { die 2 'You must specify a system name to export from'; }

me=$(whoami)
host=$(hostname)
human_now=$(date)
machine_now=$(date +'%Y%m%d-%H%M%S')

work_dir=${1:-"$RECON_WORK_DIR/$machine_now"}

[ -d "$work_dir" ] || { mkdir -p "$work_dir"; }
[ -d "$work_dir" ] || { die 1 "Unable to create working directory '$work_dir'"; }

if [ -t 1 -a $# -lt 1 ]
then
    echo "Output will be written to '$work_dir/xt_stock_export.csv'"
fi

{
    echo "# Generated by $me@$host from DB $db_name@$db_host at $human_now";
    echo 'channel,sku,status,unavailable,allocated,available';
    /opt/xt/xt-perl/bin/perl -Ilib "$RECON_BIN_DIR"/xt_export_all_sql.pl         |
        psql -U "$db_user" -d "$db_name" -h "$db_host"       |
        sed -e '1,/^-----/d' -e '/^([0-9]* rows*)/,$d' -e 's/^ *//'
} >"$work_dir"/xt_stock_export.csv 2>"$work_dir"/xt_stock_export.err

if [ -s "$work_dir"/xt_stock_export.err ]
then
    {
        echo "Errors reported:"
        cat "$work_dir"/xt_stock_export.err
        echo "End of Errors"
    } >&2

    exit 1
else
    rm -f "$work_dir"/xt_stock_export.err 
fi

exit 0
