begin;

update colour set colour = 'Animal print' where id = 91 and colour = 'Animal Print';
update colour set colour = 'Antique rose' where id = 92 and colour = 'Antique Rose';
update colour set colour = 'Cerulean' where id = 45 and colour = 'Arctic Blue';
update colour set colour = 'Baby pink' where id = 93 and colour = 'Baby pink';
update colour set colour = 'Bright blue' where id = 46 and colour = 'Bright Blue';
update colour set colour = 'Bright green' where id = 59 and colour = 'Bright Green';
update colour set colour = 'Bright pink' where id = 73 and colour = 'Bright Pink';
update colour set colour = 'Bright yellow' where id = 82 and colour = 'Bright Yellow';
update colour set colour = 'Azure' where id = 47 and colour = 'Caribbean Blue';
update colour set colour = 'Dark brown' where id = 13 and colour = 'Dark Brown';
update colour set colour = 'Dark denim' where id = 117 and colour = 'Dark Denim';
update colour set colour = 'Dark gray' where id = 14 and colour = 'Dark Gray';
update colour set colour = 'Dark green' where id = 60 and colour = 'Dark Green';
update colour set colour = 'Dark purple' where id = 86 and colour = 'Dark Purple';
update colour set colour = 'Forest green' where id = 61 and colour = 'Forest Green';
update colour set colour = 'Gray green' where id = 113 and colour = 'Gray Green';
update colour set colour = 'Intense red' where id = 78 and colour = 'Intense Red';
update colour set colour = 'Jade' where id = 63 and colour = 'Jungle Green';
update colour set colour = 'Leaf green' where id = 87 and colour = 'Leaf Green';
update colour set colour = 'Light blue' where id = 48 and colour = 'Light Blue';
update colour set colour = 'Light brown' where id = 51 and colour = 'Light Brown';
update colour set colour = 'Light denim' where id = 115 and colour = 'Light Denim';
update colour set colour = 'Light gray' where id = 58 and colour = 'Light Gray';
update colour set colour = 'Light green' where id = 24 and colour = 'Light Green';
update colour set colour = 'Lime green' where id = 88 and colour = 'Lime Green';
update colour set colour = 'Lipstick red' where id = 79 and colour = 'Lipstick Red';
update colour set colour = 'Matte gold' where id = 67 and colour = 'Matte Gold';
update colour set colour = 'Marigold' where id = 83 and colour = 'Medium Yellow';
update colour set colour = 'Mid denim' where id = 116 and colour = 'Mid Denim';
update colour set colour = 'Midnight blue' where id = 98 and colour = 'Midnight Blue';
update colour set colour = 'Mint green' where id = 120 and colour = 'Mint Green';
update colour set colour = 'Mushroom' where id = 89 and colour = 'Mouse';
update colour set colour = 'Saffron' where id = 108 and colour = 'Mustard';
update colour set colour = 'Pastel orange' where id = 70 and colour = 'Pastel Orange';
update colour set colour = 'Royal blue' where id = 111 and colour = 'Royal Blue';
update colour set colour = 'Shiny gold' where id = 68 and colour = 'Shiny Gold';
update colour set colour = 'Signal orange' where id = 71 and colour = 'Signal Orange';
update colour set colour = 'Sky blue' where id = 49 and colour = 'Sky Blue';
update colour set colour = 'Storm blue' where id = 50 and colour = 'Storm Blue';
update colour set colour = 'Pastel pink' where id = 109 and colour = 'Sugar Pink';

commit;
