#!/bin/sh

delete_files() {
    local path=$1
    local cutoff_days=$2

    find $path -mtime +$cutoff_days -delete
}

delete_barcodes() {
    local name_part=$1
    local cutoff_days=$2

    find /var/data/xt_static/print_docs/barcode/ -mtime +$cutoff_days -name "*$name_part*" -delete
}

delete_files /var/data/xt_static/print_docs/accept/ 2               # Stock sheet - 2 days
delete_files /var/data/xt_static/print_docs/addresscard/ 7          # Premier address card - 7 days
delete_files /var/data/xt_static/print_docs/dead/ 2                 # Stock sheet (dead) - 2 days
delete_files /var/data/xt_static/print_docs/delivery/ 2             # Stock sheet - 2 days
delete_files /var/data/xt_static/print_docs/dgn/ 366                # Dangerous goods declaration - 1 year
delete_files /var/data/xt_static/print_docs/fasttrack/ 2            # Fasttrack sheet - 2 days
delete_files /var/data/xt_static/print_docs/faulty/ 2               # Putaway sheet (faulty) - 2 days
delete_files /var/data/xt_static/print_docs/giftmessage/ 2          # Gift message - 2 days
delete_files /var/data/xt_static/print_docs/gift_message_images/ 2  # Gift message image - 2 days
delete_files /var/data/xt_static/print_docs/giftmessagewarning/ 2   # Gift message warning - 2 days
delete_files /var/data/xt_static/print_docs/invoice/ 2196           # Invoice - 6 years
delete_files /var/data/xt_static/print_docs/item_message/ 2         # Another gift message? - 2 days
delete_files /var/data/xt_static/print_docs/jc_rma_request/ 366     # JC RMA request - 1 year
delete_files /var/data/xt_static/print_docs/label/ 366              # DHL label - 1 year
delete_files /var/data/xt_static/print_docs/location/ 2             # Location barcode - 2 days
delete_files /var/data/xt_static/print_docs/main/ 2                 # Putaway sheet (main) - 2 days
delete_files /var/data/xt_static/print_docs/measurementform/ 2      # Measurement form - 2 days
delete_files /var/data/xt_static/print_docs/mrp_rma_request/ 366    # MRP RMA request - 1 year
delete_files /var/data/xt_static/print_docs/nap_rma_request/ 366    # NAP RMA request - 1 year
delete_files /var/data/xt_static/print_docs/outpro/ 2196            # Proforma invoice - 6 years
delete_files /var/data/xt_static/print_docs/out_rma_request/ 366    # Outnet RMA request - 1 year
delete_files /var/data/xt_static/print_docs/pickinglist/ 2          # Picking list - 2 days
delete_files /var/data/xt_static/print_docs/prmretnote/ 31          # Collection note - 1 month
delete_files /var/data/xt_static/print_docs/recode/ 2               # Putaway sheet (recode) - 2 days
delete_files /var/data/xt_static/print_docs/retpro/ 2196            # Return proforma invoice - 6 years
delete_files /var/data/xt_static/print_docs/return_delivery/ 366    # Arrivals in Delivery - 1 year
delete_files /var/data/xt_static/print_docs/returndel/ 7            # Stock sheet (returns) - 7 days
delete_files /var/data/xt_static/print_docs/rtv/ 7                  # Stock sheet (RTV Workstation) - 7 days
delete_files /var/data/xt_static/print_docs/rtv_inspect_picklist/ 2 # RTV inspection picking list - 2 days
delete_files /var/data/xt_static/print_docs/rtv_ship_picklist/ 2    # RTV picking list - 2 days
delete_files /var/data/xt_static/print_docs/shippingform/ 93        # Shipping input form - 3 months
delete_files /var/data/xt_static/print_docs/surplus/ 2              # Putaway sheet (surplus) - 2 days

# All (or a lot of) the barcodes end up in /barcode/, so we can't have
# a policy that fits that whole dir. But we can clean some of them out
# with limits matching the longest-lived docs that use them:
delete_barcodes pickorder 93  # Used in shipping form and pickinglist
delete_barcodes delivery  366 # Used in putaway, returns (main, rtv, dead, putaway, fasttrack, return_delivery)

