#!/opt/xt/xt-perl/bin/perl

use NAP::policy 'tt';

use FindBin::libs;
use FindBin::libs qw( base=lib_dynamic );

use XTracker::Script::Product::MeasurementImporter;

=head1 NAME

import_product_measurements

=head1 SYNOPSIS

./import_product_measurements

=head1 DESCRIPTION

This script will pick up CSV files dropped onto a Samba share by Cubiscan, and
update products with measurements.

=cut

XTracker::Script::Product::MeasurementImporter->new->invoke;

exit(0);
