#!/opt/xt/xt-perl/bin/perl
use NAP::policy;
use FindBin::libs;
use FindBin::libs 'base=lib_dynamic';

use XTracker::CSV::Importer::LatePostcodes;

die "Error: Require a CSV file to import from\n" unless $ARGV[0];
my $csv_file_path = $ARGV[0];

open(my $fh, '<', $csv_file_path);
my $rows_imported = XTracker::CSV::Importer::LatePostcodes->new->import_to_database({
    file_handle => $fh,
});
close($fh);

print "Done. $rows_imported rows imported\n";
