#!/opt/xt/xt-perl/bin/perl

use NAP::policy "tt";

use FindBin::libs 'base=lib_dynamic';

use XTracker::Script::Stock::QuantityAdjust;

=head1 NAME

quantity_adjust - A script to adjust a sku's quantity at a location

=head1 SYNOPSIS

    quantity_adjust -s 9999-999 -l 'Transfer Pending' -d -2

=head1 DESCRIPTION

This script will adjust the quantity of the given sku at the given location.

=head1 OPTIONS

=over

=item sku|s

The sku to adjust.

=item location|l

A location name.

=item delta|d

The delta to update the quantity by. This is explicitly a delta as absolutes
can be dangerous. Note that you need to pass negative integers to remove
items.

=back

=cut

use Getopt::Long;
use Pod::Usage;

my %opt;
my $result = GetOptions( \%opt,
    'sku|s=s', 'location|l=s', 'delta|d=i', 'help|h|?',
);

pod2usage(1) if !$result || $opt{help};

XTracker::Script::Stock::QuantityAdjust->new->invoke(%opt);
