Vagrant.configure(2) do |config|
  # Online documentation for this file available at https://docs.vagrantup.com.

  config.vm.box = "chef/centos-6.6"

  config.vm.network "forwarded_port", guest: 8080, host: 4242

  config.vm.provider "virtualbox" do |vb|
   vb.memory = "2048"
  end

  # TODO: Setup puppet (or something else) to do this for us
  latest_java = "/usr/java/latest"
  config.vm.provision "shell", inline: <<-SHELL
    sudo cp /vagrant/vagrant-setup/*.repo /etc/yum.repos.d/
    sudo yum clean all -y
    sudo yum upgrade -y
    sudo yum install java-1.8.0-openjdk -y
    sudo yum install git -y
    sudo yum install rpm-build -y
    sudo yum install mysql-server -y
    sudo yum install liquibase -y
    sudo service mysqld start
    sudo chkconfig --levels 235 mysqld on
    sudo yum install mlocate -y
    echo 'export IT_SERVER_PORT='8080'' >> /home/vagrant/.bashrc
    echo 'export IT_SERVER_HOST='0.0.0.0'' >> /home/vagrant/.bashrc
    sudo echo '[mysqld]\ndatadir=/var/lib/mysql\nsocket=/var/lib/mysql/mysql.sock\nuser=mysql\nsymbolic-links=0\nsql_mode=ANSI_QUOTES' > /etc/my.cnf
    sudo service mysqld restart
    sudo update-alternatives --install /usr/bin/java java #{latest_java}/bin/java 1
    sudo update-alternatives --install /usr/bin/javac javac #{latest_java}/bin/javac 1
    sudo update-alternatives --set java #{latest_java}/bin/java
    sudo update-alternatives --set javac #{latest_java}/bin/javac
    sudo yum install mysql-connector-java -y
    cd /vagrant/
    ./db/refresh_dev_db
    echo 'export TEST_URL='http://0.0.0.0:8080'' >> /home/vagrant/.bashrc
    echo 'export JAVA_HOME="#{latest_java}"' >> /home/vagrant/.bashrc
    echo 'export PATH=$PATH:$JAVA_HOME/bin' >> /home/vagrant/.bashrc
  SHELL
end
