#!/usr/bin/env perl
use strict;
use warnings;
use feature ':5.10';
use File::Slurp;
use JSON;

die qq{usage: $0 file} unless $ARGV[0];
my $d=read_file($ARGV[0]);
my $p=from_json($d);
my $t=to_json($p,{pretty=>1});
say $t;
