--CANDO-2562 : Add Premier Shipping County's for HK

BEGIN WORK;

INSERT INTO state_shipping_charge (state, country_id, shipping_charge_id, channel_id) VALUES
('Aberdeen', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Admiralty', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Ap Lei Chau', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Causeway Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Central', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Chai Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Cyberport', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Deep Water Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Fortress Hill', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Happy Valley', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Heng Fa Chuen', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kennedy Town', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Mid-Levels', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('North Point', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Pok Fu Lam', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Quarry Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Repulse Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sai Wan Ho', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sai Ying Pun', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shau Kei Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shek O', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sheung Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shouson Hill', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Stanley', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Stubbs Road', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tai Hang', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tai Koo', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('The Peak', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tin Hau', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Wan Chai', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Wong Chuk Hang', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Cheung Sha Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Choi Hung', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Choi Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Diamond Hill', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Ho Man Tin', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Hung Hom', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Jordan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kowloon Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kowloon City', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kowloon Tong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kwun Tong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lai Chi Kok', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lam Tin', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lei Yue Mun', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lok Fu', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Mei Foo', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Mong Kok', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Ngau Tau Kok', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Prince Edward', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('San Po Kong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sham Shui Po', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shek Kip Mei', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tai Kwok Tsui', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('To Kwa Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tsim Sha Tsui', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tsz Wan Shan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Whampoa Garden', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Wong Tai Sin', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Yau Ma Tei', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Yau Tong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000324-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Aberdeen', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Admiralty', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Ap Lei Chau', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Causeway Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Central', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Chai Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Cyberport', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Deep Water Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Fortress Hill', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Happy Valley', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Heng Fa Chuen', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kennedy Town', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Mid-Levels', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('North Point', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Pok Fu Lam', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Quarry Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Repulse Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sai Wan Ho', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sai Ying Pun', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shau Kei Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shek O', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sheung Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shouson Hill', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Stanley', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Stubbs Road', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tai Hang', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tai Koo', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('The Peak', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tin Hau', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Wan Chai', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Wong Chuk Hang', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Cheung Sha Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Choi Hung', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Choi Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Diamond Hill', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Ho Man Tin', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Hung Hom', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Jordan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kowloon Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kowloon City', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kowloon Tong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kwun Tong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lai Chi Kok', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lam Tin', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lei Yue Mun', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lok Fu', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Mei Foo', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Mong Kok', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Ngau Tau Kok', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Prince Edward', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('San Po Kong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sham Shui Po', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shek Kip Mei', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tai Kwok Tsui', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('To Kwa Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tsim Sha Tsui', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tsz Wan Shan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Whampoa Garden', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Wong Tai Sin', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Yau Ma Tei', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Yau Tong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000323-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Aberdeen', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Admiralty', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Ap Lei Chau', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Causeway Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Central', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Chai Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Cyberport', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Deep Water Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Fortress Hill', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Happy Valley', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Heng Fa Chuen', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kennedy Town', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Mid-Levels', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('North Point', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Pok Fu Lam', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Quarry Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Repulse Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sai Wan Ho', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sai Ying Pun', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shau Kei Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shek O', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sheung Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shouson Hill', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Stanley', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Stubbs Road', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tai Hang', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tai Koo', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('The Peak', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tin Hau', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Wan Chai', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Wong Chuk Hang', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Cheung Sha Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Choi Hung', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Choi Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Diamond Hill', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Ho Man Tin', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Hung Hom', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Jordan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kowloon Bay', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kowloon City', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kowloon Tong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Kwun Tong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lai Chi Kok', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lam Tin', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lei Yue Mun', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Lok Fu', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Mei Foo', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Mong Kok', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Ngau Tau Kok', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Prince Edward', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('San Po Kong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Sham Shui Po', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Shek Kip Mei', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tai Kwok Tsui', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('To Kwa Wan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tsim Sha Tsui', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Tsz Wan Shan', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Whampoa Garden', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Wong Tai Sin', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Yau Ma Tei', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') ),
('Yau Tong', (select id from country where country = 'Hong Kong'),
 (select id from shipping_charge where sku='9000320-001' and channel_id = ( SELECT id FROM channel WHERE name = 'NET-A-PORTER.COM')),
 (select id from channel where name = 'NET-A-PORTER.COM') );

COMMIT WORK;
