
BEGIN;

-- NAP INTL

INSERT INTO postcode_shipping_charge(postcode, country_id, shipping_charge_id, channel_id) VALUES
  ('BB12' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BB7'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BB8'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BB9'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BB94' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BL0'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BL11' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BL7'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BL78' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BL8'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('BL9'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('DY10' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('DY12' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('DY13' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('DY14' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('FK18' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('FK19' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('G82'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M11'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M12'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M19'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M25'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M26'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M29'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M30'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M38'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M50'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M60'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M61'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('M9'   , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('N12'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('OL10' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('OL13' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('OL14' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('OL15' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('OL2'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('OL3'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('OL5'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('PR25' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('PR26' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('SK12' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('SK13' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('SK15' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('SK2'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('SK3'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('SK4'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('SK9'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('ST16' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('ST17' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('ST18' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('WA15' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('WN7'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('WV98' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL')) ,
  ('WV99' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000218-001') , (SELECT id FROM channel WHERE web_name = 'NAP-INTL'));


-- MRP INTL

INSERT INTO postcode_shipping_charge(postcode, country_id, shipping_charge_id, channel_id) VALUES
  ('BB12' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BB7'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BB8'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BB9'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BB94' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BL0'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BL11' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BL7'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BL78' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BL8'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('BL9'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('DY10' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('DY12' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('DY13' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('DY14' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('FK18' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('FK19' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('G82'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M11'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M12'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M19'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M25'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M26'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M29'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M30'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M38'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M50'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M60'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M61'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('M9'   , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('N12'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('OL10' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('OL13' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('OL14' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('OL15' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('OL2'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('OL3'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('OL5'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('PR25' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('PR26' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('SK12' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('SK13' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('SK15' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('SK2'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('SK3'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('SK4'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('SK9'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('ST16' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('ST17' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('ST18' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('WA15' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('WN7'  , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('WV98' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL')) ,
  ('WV99' , (SELECT id FROM country WHERE code = 'GB') , (SELECT id FROM shipping_charge WHERE sku = '9000216-001') , (SELECT id FROM channel WHERE web_name = 'MRP-INTL'));

COMMIT;
