BEGIN;

-- Add pack station 33-52 and associated printers

-- Add pack stations
INSERT INTO system_config.config_group (name)
VALUES  ('PackingStation_33'),
        ('PackingStation_34'),
        ('PackingStation_35'),
        ('PackingStation_36'),
        ('PackingStation_37'),
        ('PackingStation_38'),
        ('PackingStation_39'),
        ('PackingStation_40'),
        ('PackingStation_41'),
        ('PackingStation_42'),
        ('PackingStation_43'),
        ('PackingStation_44'),
        ('PackingStation_45'),
        ('PackingStation_46'),
        ('PackingStation_47'),
        ('PackingStation_48'),
        ('PackingStation_49'),
        ('PackingStation_50'),
        ('PackingStation_51'),
        ('PackingStation_52')
;

-- Add pack stations to each channel
INSERT INTO system_config.config_group_setting (
                config_group_id, setting, value, sequence
            )
VALUES ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_33',
         33 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_34',
         34 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_35',
         35 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_36',
         36 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_37',
         37 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_38',
         38 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_39',
         39 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_40',
         40 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_41',
         41 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_42',
         42 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_43',
         43 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_44',
         44 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_45',
         45 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_46',
         46 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_47',
         47 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_48',
         48 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_49',
         49 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_50',
         50 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_51',
         51 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 2),
         'packing_station',
         'PackingStation_52',
         52 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_33',
         33 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_34',
         34 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_35',
         35 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_36',
         36 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_37',
         37 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_38',
         38 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_39',
         39 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_40',
         40 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_41',
         41 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_42',
         42 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_43',
         43 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_44',
         44 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_45',
         45 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_46',
         46 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_47',
         47 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_48',
         48 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_49',
         49 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_50',
         50 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_51',
         51 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 4),
         'packing_station',
         'PackingStation_52',
         52 ),

       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_33',
         33 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_34',
         34 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_35',
         35 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_36',
         36 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_37',
         37 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_38',
         38 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_39',
         39 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_40',
         40 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_41',
         41 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_42',
         42 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_43',
         43 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_44',
         44 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_45',
         45 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_46',
         46 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_47',
         47 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_48',
         48 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_49',
         49 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_50',
         50 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_51',
         51 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 6),
         'packing_station',
         'PackingStation_52',
         52 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_33',
         33 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_34',
         34 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_35',
         35 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_36',
         36 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_37',
         37 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_38',
         38 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_39',
         39 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_40',
         40 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_41',
         41 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_42',
         42 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_43',
         43 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_44',
         44 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_45',
         45 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_46',
         46 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_47',
         47 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_48',
         48 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_49',
         49 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_50',
         50 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_51',
         51 ),
       ( (SELECT id FROM system_config.config_group WHERE name = 'PackingStationList' AND channel_id = 8),
         'packing_station',
         'PackingStation_52',
         52 )
;

-- Right. That's all the pack stations on all the channels added. 


INSERT INTO system_config.config_group_setting (
                config_group_id, setting, value
            )
VALUES ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_33' ),
         'doc_printer', 'Packing Doc Prn 09' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_33' ),
         'lab_printer', 'Packing Lab Prn 33' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_34' ),
         'doc_printer', 'Packing Doc Prn 10' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_34' ),
         'lab_printer', 'Packing Lab Prn 34' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_35' ),
         'doc_printer', 'Packing Doc Prn 11' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_35' ),
         'lab_printer', 'Packing Lab Prn 35' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_36' ),
         'doc_printer', 'Packing Doc Prn 11' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_36' ),
         'lab_printer', 'Packing Lab Prn 36' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_37' ),
         'doc_printer', 'Packing Doc Prn 11' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_37' ),
         'lab_printer', 'Packing Lab Prn 37' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_38' ),
         'doc_printer', 'Packing Doc Prn 11' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_38' ),
         'lab_printer', 'Packing Lab Prn 38' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_39' ),
         'doc_printer', 'Packing Doc Prn 12' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_39' ),
         'lab_printer', 'Packing Lab Prn 39' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_40' ),
         'doc_printer', 'Packing Doc Prn 12' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_40' ),
         'lab_printer', 'Packing Lab Prn 40' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_41' ),
         'doc_printer', 'Packing Doc Prn 12' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_41' ),
         'lab_printer', 'Packing Lab Prn 41' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_42' ),
         'doc_printer', 'Packing Doc Prn 12' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_42' ),
         'lab_printer', 'Packing Lab Prn 42' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_43' ),
         'doc_printer', 'Packing Doc Prn 13' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_43' ),
         'lab_printer', 'Packing Lab Prn 43' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_44' ),
         'doc_printer', 'Packing Doc Prn 13' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_44' ),
         'lab_printer', 'Packing Lab Prn 44' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_45' ),
         'doc_printer', 'Packing Doc Prn 13' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_45' ),
         'lab_printer', 'Packing Lab Prn 45' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_46' ),
         'doc_printer', 'Packing Doc Prn 13' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_46' ),
         'lab_printer', 'Packing Lab Prn 46' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_47' ),
         'doc_printer', 'Packing Doc Prn 14' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_47' ),
         'lab_printer', 'Packing Lab Prn 47' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_48' ),
         'doc_printer', 'Packing Doc Prn 14' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_48' ),
         'lab_printer', 'Packing Lab Prn 48' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_49' ),
         'doc_printer', 'Packing Doc Prn 14' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_49' ),
         'lab_printer', 'Packing Lab Prn 49' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_50' ),
         'doc_printer', 'Packing Doc Prn 14' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_50' ),
         'lab_printer', 'Packing Lab Prn 50' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_51' ),
         'doc_printer', 'Packing Doc Prn 15' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_51' ),
         'lab_printer', 'Packing Lab Prn 51' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_52' ),
         'doc_printer', 'Packing Doc Prn 15' ),
       ( ( SELECT id FROM system_config.config_group WHERE name = 'PackingStation_52' ),
         'lab_printer', 'Packing Lab Prn 52' )

;



COMMIT;
