#!/opt/xt/xt-perl/bin/perl
use NAP::policy;
use strict;
use warnings;
use lib '/opt/xt/deploy/xtracker/lib';
use lib '/opt/xt/deploy/xtracker/lib_dynamic';
use XT::JobQueue;
use XTracker::Database 'schema_handle';

=head1 NAME

script/test/PM2054-jobs-for-lockwait [count]

=pod DESCRIPTION

This script updates name and style_notes for PIDs 21074 and 37308.

It adds 'count' updates per PID, and defaults to 5 if not specified.

=head1 AUTHOR

Chisel Wright C<< <chisel.wright@net-a-porter.com> >>

=cut

my @pids_to_change = qw/ 21074 37308 /;
my $times_to_change = $ARGV[0] || 5;

for ( 1 .. $times_to_change ) {
    foreach my $pid (@pids_to_change) {
        # get a new queuing object
        my $queuer = XT::JobQueue->new;

        say "queuing XT::JQ::DC::Receive::Product::Update job for $pid";

        # insert the receive-update task
        $queuer->insert_job(
            'XT::JQ::DC::Receive::Product::Update',
            {
                feedback_to     => {
                    operators       => [ 399 ],
                },
                export_to_website           => 1,
                payload => [
                    {
                        product_id          => $pid,
                        operator_id         => 399,

                        name                => 'PM-2054 # ' . scalar(localtime),
                        style_notes         => 'PM-2054 @ ' . scalar(localtime),
                    },
                ],
            }
        ) or die $!;
    }
}

# some user feedback
say "done";
